// ecoregions.js — Native plant checklists for each ecoregion (prestige system)
// Plant data sourced from Homegrown National Park (homegrownnationalpark.org)
// Insect hosting data based on Doug Tallamy's research ("Bringing Nature Home",
// "Nature's Best Hope") and NWF Native Plant Finder.
//
// Each ecoregion is a prestige tier. Completing all plants in a region unlocks
// the next region and awards a permanent biosphere multiplier.

// ── Wildlife-type icons ───────────────────────────────────────────────────────
export const WILDLIFE_TYPE_ICONS = {
  butterfly: '🦋',
  moth:      '🌙',
  bee:       '🐝',
  fly:       '🪰',
  beetle:    '🪲',
  wasp:      '⚗️',
  bird:      '🐦',
  mammal:    '🐿️',
};

// ── Ecoregion definitions ─────────────────────────────────────────────────────
export const ECOREGIONS = [
  {
    id:    'se_usa_plains',
    code:  '8.3',
    name:  'SE USA Plains',
    label: '8.3 – SE USA Plains',
    icon:  '🌲',
    desc:  'The rolling mixed forests and open plains of Alabama, Georgia, and the Carolinas. Defined by longleaf pine savannas, oak-hickory woodlands, and warm, humid summers that support extraordinary insect diversity.',
    hnpUrl: 'https://homegrownnationalpark.org/keystone-plants/?_ecoregion=8-3-se-usa-plains',
    prestigeRequires: null, // first region — always available
    prestigeReward:   'Unlocks 8.4 – Ozark/Ouachita-Appalachian Forests · +10% conservation point generation',

    plants: [

      // ══ FLOWERS ════════════════════════════════════════════════════════════

      {
        id:               'scarlet_strawberry',
        requiresResearch: [],
        name:             'Scarlet Strawberry',
        sci:  'Fragaria virginiana',
        icon: '🍓',
        type: 'flower',
          hasFruit: true,
        desc: 'Our native wild strawberry spreads by runners to form a low, dense groundcover. Tiny white flowers in spring give way to small, intensely flavored red fruits. Tolerates a wide range of soils and light conditions. Container friendly.',
        height: '< 1 ft',
        seasonOfInterest: 'Spring',
        insectsHosted: [
          { name: 'Two-banded Skipper', sci: 'Pyrgus ruralis', type: 'butterfly',
            role: 'Larval host plant', note: 'Caterpillars feed on wild strawberry leaves, making this plant essential for this regionally rare skipper.' },
          { name: 'Gray Hairstreak', sci: 'Strymon melinus', type: 'butterfly',
            role: 'Larval host plant', note: 'Larvae bore into the flower buds and developing fruits — an intimate relationship that predates cultivation.' },
          { name: "Carlin's Mining Bee", sci: 'Andrena carlini', type: 'bee',
            role: 'Early-season pollen source', note: "One of the first native bees active each spring, Carlin's Mining Bee nests in bare soil and specializes in early-blooming flowers — wild strawberry pollen is among its primary resources." },
          { name: "Nason's Mining Bee", sci: 'Andrena nasonii', type: 'bee',
            role: 'Early-season pollen source', note: "A common spring mining bee throughout the SE USA, Nason's Mining Bee builds nest burrows in hard-packed paths and garden beds, timing emergence precisely to the wild strawberry bloom." },
          { name: 'Ligated Furrow Bee', sci: 'Halictus ligatus', type: 'bee',
            role: 'Nectar & pollen source', note: 'One of the most abundant native bees in eastern North America, the Ligated Furrow Bee forms small ground colonies and arrives at strawberry blooms throughout the day for both pollen and nectar.' },
          { name: 'Bicolored Sweat Bee', sci: 'Agapostemon virescens', type: 'bee',
            role: 'Nectar & pollen source', note: 'Easily identified by its metallic-green head and striped abdomen, this communal ground-nesting sweat bee is among the earliest native bee visitors to wild strawberry each spring.' },
        ],
        wildlifeNote: 'Robins, thrushes, box turtles, and white-footed mice all rely on the fruits. The plant\'s low mat provides cover for ground-nesting insects.',
        caterpillarSpp: 14,
        biosphereBonus: 5,
        cost: 20,
        duration: 7,
      },

      {
        id:               'white_yarrow',
        requiresResearch: [],
        name:             'White Yarrow',
        sci:  'Achillea millefolium',
        icon: '🌼',
        type: 'flower',
        desc: 'Flat-topped clusters of tiny white flowers on ferny, aromatic foliage. Blooms from summer through fall, tolerates drought and poor soil, and spreads to form dense colonies. Has been an important medicinal herb for millennia. Container friendly.',
        height: '1–2 ft',
        seasonOfInterest: 'Summer through Fall',
        insectsHosted: [
          { name: 'Margined Calligrapher', sci: 'Toxomerus marginatus', type: 'fly',
            role: 'Nectar source & aphid predator', note: 'The most abundant hoverfly in eastern North America, instantly recognizable by the yellow calligraphic markings on its abdomen. Adults fuel on yarrow nectar; their larvae are voracious aphid predators — a single larva can consume 400 aphids before pupating.' },
          { name: 'Yellow Ophion', sci: 'Ophion flavidus', type: 'wasp',
            role: 'Nectar source', note: "This slender, reddish-amber parasitoid wasp fuels on yarrow's open flowers by day while searching for moth caterpillars to parasitize. Its larvae develop inside living hosts — providing silent but powerful pest control." },
          { name: "Say's Netelia", sci: 'Netelia sayi', type: 'wasp',
            role: 'Nocturnal nectar source', note: 'A nocturnal ichneumon wasp that visits open flowers after dark. It parasitizes moth pupae in the soil, forming an invisible link between the garden surface and the underground insect world.' },
          { name: 'Pearl Crescent', sci: 'Phyciodes tharos', type: 'butterfly',
            role: 'Nectar source', note: 'One of the most common SE butterflies, nectar-fueling continuously between spring and fall on a wide range of blooms.' },
          { name: 'Zephyr Sweat Bee', sci: 'Lasioglossum zephyrum', type: 'bee',
            role: 'Pollen & nectar source', note: 'One of the most commonly encountered Lasioglossum species in the SE USA. Forms small communal nests in the ground and consistently forages on open, accessible flowers like yarrow for both pollen and nectar.' },
          { name: 'Broken-banded Sweat Bee', sci: 'Lasioglossum imitatum', type: 'bee',
            role: 'Pollen & nectar source', note: 'A small native bee highly tolerant of disturbed habitats. On yarrow, both sexes are active from late spring through fall — one of the longest foraging seasons of any native bee in the region.' },
          { name: 'Painted Lady', sci: 'Vanessa cardui', type: 'butterfly',
            role: 'Nectar source', note: 'This globe-trotting butterfly undertakes remarkable multigenerational migrations and stops at yarrow throughout its range.' },
        ],
        wildlifeNote: 'The dried seed heads persist through winter, providing seeds for goldfinches and sparrows. Dense basal foliage creates micro-shelters for beetles and spiders.',
        caterpillarSpp: 9,
        biosphereBonus: 5,
        cost: 20,
        duration: 7,
      },

      {
        id:               'late_boneset',
        requiresResearch: ['wildflower_margins'],
        name:             'Late Boneset',
        sci:  'Eupatorium serotinum',
        icon: '🌿',
        type: 'flower',
        desc: 'A tall, late-blooming native with dense clusters of tiny white flowers. Blooms in late summer through fall when few other plants offer nectar — critical for pollinators preparing for winter and for migrating Monarchs fueling up for their journey.',
        height: '4–5 ft',
        seasonOfInterest: 'Late Summer through Fall',
        insectsHosted: [
          { name: 'Monarch', sci: 'Danaus plexippus', type: 'butterfly',
            role: 'Critical late-season nectar', note: 'Monarchs migrating south to Mexico must double their body weight in fat reserves. Late-blooming bonesets are among the most important fuel stops on their journey.' },
          { name: 'Queen Butterfly', sci: 'Danaus gilippus', type: 'butterfly',
            role: 'Nectar source', note: 'The Queen, a close relative of the Monarch, is a boneset specialist throughout the SE USA and is easily missed by those who don\'t grow it.' },
          { name: 'Eastern Tiger Swallowtail', sci: 'Papilio glaucus', type: 'butterfly',
            role: 'Nectar source', note: 'The SE USA\'s largest butterfly is a reliable boneset visitor. Its caterpillars feed on cherry, tulip poplar, and ash — not boneset — so every adult you see is here purely for fuel.' },
          { name: 'Eastern Bumblebee', sci: 'Bombus impatiens', type: 'bee',
            role: 'Nectar & pollen', note: "The most common bumblebee in eastern North America. On late boneset, queens gather their final fat reserves before seeking an overwintering burrow — this late bloom may determine whether a colony's queens survive to spring." },
          { name: 'Brown-belted Bumblebee', sci: 'Bombus griseocollis', type: 'bee',
            role: 'Nectar & pollen', note: 'Distinguished by a distinctive brown belt across the second abdominal segment. A frequent late-season boneset visitor, it works quickly through dense flower clusters to maximize pollen and nectar collection.' },
          { name: 'American Bumblebee', sci: 'Bombus pensylvanicus', type: 'bee',
            role: 'Nectar & pollen', note: 'Once the most abundant bumble bee in the SE USA, the American Bumblebee has declined sharply and is a species of conservation concern. Late boneset blooms provide the critical late-season resources its queens depend on.' },
          { name: 'Guinea Paper Wasp', sci: 'Polistes exclamans', type: 'wasp',
            role: 'Nectar source', note: 'The most common paper wasp in the SE USA. Adults fuel on boneset nectar between hunting runs for caterpillars, which they macerate and feed to their developing larvae — a direct benefit to surrounding crops.' },
          { name: 'Red Paper Wasp', sci: 'Polistes carolina', type: 'wasp',
            role: 'Nectar source', note: 'A striking rust-red wasp common throughout the SE USA. It builds its open-celled paper nest under eaves and logs, and fuels on boneset nectar between predatory foraging bouts.' },
        ],
        wildlifeNote: 'Seeds are wind-dispersed, and the fluffy seed heads attract goldfinches in autumn. Dense stands provide shelter for overwintering insects.',
        caterpillarSpp: 28,
        biosphereBonus: 6,
        cost: 22,
        duration: 10,
      },

      {
        id:               'calico_aster',
        requiresResearch: ['wildflower_margins'],
        name:             'Calico Aster',
        sci:  'Symphyotrichum lateriflorum',
        icon: '✨',
        type: 'flower',
        desc: 'A profusely-branching native aster with hundreds of tiny white flowers with yellow to purple centres. Blooms in late fall when nearly everything else has gone to seed, providing a final surge of nectar for migrating insects. Tolerates shade and dry soil.',
        height: '2–4 ft',
        seasonOfInterest: 'Fall',
        insectsHosted: [
          { name: 'Pearl Crescent', sci: 'Phyciodes tharos', type: 'butterfly',
            role: 'Specialist larval host', note: 'The Pearl Crescent is an aster specialist — larvae feed exclusively on Symphyotrichum foliage. Without native asters, there are no Pearl Crescents.' },
          { name: 'Silvery Checkerspot', sci: 'Chlosyne nycteis', type: 'butterfly',
            role: 'Larval host & nectar', note: 'Larvae feed on aster and Rudbeckia foliage in communal silk tents. Adults nectar on asters in late summer and fall.' },
          { name: 'Aster Specialist Bee', sci: 'Colletes inaequalis', type: 'bee',
            role: 'Pollen specialist', note: 'This ground-nesting native bee collects pollen almost entirely from asters. It cannot survive without them — a stark example of plant-insect co-evolution.' },
          { name: 'Aster Mining Bee', sci: 'Andrena asteris', type: 'bee',
            role: 'Pollen specialist', note: 'A true aster specialist: females will fly past fields of other flowers to find asters. Nests in small colonies in sandy, bare soil.' },
          { name: 'Eastern Bumblebee', sci: 'Bombus impatiens', type: 'bee',
            role: 'Late-season nectar & pollen', note: 'Eastern Bumblebees work calico aster intensively in fall, each queen making hundreds of flower visits to store enough energy for the winter and to found a new colony in spring.' },
          { name: 'Brown-belted Bumblebee', sci: 'Bombus griseocollis', type: 'bee',
            role: 'Late-season nectar & pollen', note: "Calico aster's October bloom arrives just as most wildflowers have finished, making it a critical last stop for Brown-belted Bumblebees preparing to hibernate." },
          { name: 'American Bumblebee', sci: 'Bombus pensylvanicus', type: 'bee',
            role: 'Late-season nectar & pollen', note: 'This declining bumblebee depends on abundant late-season blooms. Aster plantings directly support overwinter survival of this conservation-priority species by providing resources when almost nothing else is blooming.' },
        ],
        wildlifeNote: 'The fluffy seed heads are eaten by American Goldfinches, Dark-eyed Juncos, and White-throated Sparrows throughout winter.',
        caterpillarSpp: 112,
        biosphereBonus: 7,
        cost: 25,
        duration: 10,
      },

      {
        id:               'blue_wood_aster',
        requiresResearch: ['wildflower_margins'],
        name:             'Blue Wood Aster',
        sci:  'Symphyotrichum cordifolium',
        icon: '💜',
        type: 'flower',
        desc: 'A shade-tolerant aster with airy sprays of small lavender-blue flowers on arching stems. One of the few native plants that blooms heavily in partial to full shade, making it invaluable for woodland garden edges. Heart-shaped basal leaves are distinctive.',
        height: '2–4 ft',
        seasonOfInterest: 'Fall',
        insectsHosted: [
          { name: 'Pearl Crescent', sci: 'Phyciodes tharos', type: 'butterfly',
            role: 'Specialist larval host', note: 'Blue wood aster is one of several Symphyotrichum species that Pearl Crescent larvae depend on. In shaded woodland settings, this aster may be the only option.' },
          { name: 'Harris\' Checkerspot', sci: 'Chlosyne harrisii', type: 'butterfly',
            role: 'Larval host', note: 'This regionally localized butterfly uses flat-topped asters as its primary larval host. Local populations can become established when this aster is planted in suitable habitat.' },
          { name: 'Zephyr Sweat Bee', sci: 'Lasioglossum zephyrum', type: 'bee',
            role: 'Nectar & pollen', note: 'In shaded garden settings where larger bees are less active, the Zephyr Sweat Bee thrives — arriving consistently throughout the blue wood aster bloom and visiting far more flowers per hour than any bumble bee could in low light.' },
          { name: 'Broken-banded Sweat Bee', sci: 'Lasioglossum imitatum', type: 'bee',
            role: 'Nectar & pollen', note: 'In the partial shade of woodland gardens, small Lasioglossum bees often become the dominant flower visitor — filling the pollination role that larger bees cannot perform in low-light understory settings.' },
          { name: 'Monarch', sci: 'Danaus plexippus', type: 'butterfly',
            role: 'Fall migration nectar', note: 'One of the last blooming native plants, blue wood aster provides critical fuel for Monarch butterflies on their fall migration to Mexico.' },
        ],
        wildlifeNote: 'Grows in the understory where few other nectar plants thrive, creating habitat in otherwise insect-poor garden zones.',
        caterpillarSpp: 112,
        biosphereBonus: 7,
        cost: 25,
        duration: 10,
      },

      {
        id:               'wrinkleleaf_goldenrod',
        requiresResearch: ['pollinator_survey'],
        name:             'Wrinkleleaf Goldenrod',
        sci:  'Solidago rugosa',
        icon: '🌕',
        type: 'flower',
        desc: 'Arching sprays of bright yellow flowers on distinctive wrinkled-leaf stems. Tolerates wet conditions and supports over 100 species of insects — one of the most wildlife-valuable plants for its small footprint. Deer-resistant. Container friendly.',
        height: '3–5 ft',
        seasonOfInterest: 'Late Summer through Fall',
        insectsHosted: [
          { name: 'Goldenrod Specialist Bee', sci: 'Colletes solidaginis', type: 'bee',
            role: 'Pollen specialist', note: 'This bee collects pollen from goldenrod and nothing else. It times its emergence perfectly with goldenrod bloom and cannot complete its life cycle without it.' },
          { name: 'Goldenrod Mining Bee', sci: 'Andrena solidaginis', type: 'bee',
            role: 'Pollen specialist', note: 'Another obligate goldenrod specialist. You can identify it by the dense golden pollen loads on its back legs — pollen that came only from goldenrod.' },
          { name: 'Goldenrod Gall Fly', sci: 'Eurosta solidaginis', type: 'fly',
            role: 'Gall-forming specialist', note: 'This fly lays its eggs in goldenrod stems, forming round galls. In winter, Downy Woodpeckers peck open these galls to eat the fat-rich larvae — a remarkable food web link.' },
          { name: 'Pearl Crescent', sci: 'Phyciodes tharos', type: 'butterfly',
            role: 'Nectar source', note: 'Pearl Crescents nectaring on goldenrod in late summer are a quintessential sight of the eastern landscape — a scene that disappears when goldenrod is replaced with ornamentals.' },
          { name: 'Monarch', sci: 'Danaus plexippus', type: 'butterfly',
            role: 'Migration fuel nectar', note: 'Goldenrod and milkweed are the two most important plants for Monarchs. Goldenrod provides the nectar they need to deposit fat for the 2,500-mile migration to Mexico.' },
          { name: 'Locust Borer', sci: 'Megacyllene robiniae', type: 'beetle',
            role: 'Nectar source', note: 'This strikingly yellow-banded longhorn beetle is a goldenrod nectar specialist as an adult, even though its larvae bore into black locust trees entirely separately.' },
        ],
        wildlifeNote: 'The dried seed heads attract dozens of songbird species over winter. Goldenrod is falsely blamed for hay fever — the real culprit is ragweed, which blooms simultaneously.',
        caterpillarSpp: 115,
        biosphereBonus: 8,
        cost: 25,
        duration: 10,
      },

      {
        id:               'old_field_goldenrod',
        requiresResearch: ['pollinator_survey'],
        name:             'Old-field Goldenrod',
        sci:  'Solidago nemoralis',
        icon: '🌾',
        type: 'flower',
        desc: 'The classic goldenrod of dry, open old fields and road margins. More drought-tolerant than most goldenrods, thriving in sandy or rocky soils where few other plants survive. Its late bloom provides critical fall resources where habitat is otherwise sparse.',
        height: '1–3 ft',
        seasonOfInterest: 'Late Summer through Fall',
        insectsHosted: [
          { name: 'Goldenrod Specialist Bee', sci: 'Colletes solidaginis', type: 'bee',
            role: 'Pollen specialist', note: 'Even in dry, disturbed habitats, specialist goldenrod bees seek out this species — demonstrating how native plants maintain food webs in degraded landscapes.' },
          { name: 'Autumn-Tailed Skipper', sci: 'Hesperia attalus', type: 'butterfly',
            role: 'Nectar source', note: 'An SE USA grassland specialist that has declined severely with native grass loss. Where it persists, goldenrods sustain its adults through fall.' },
          { name: 'Eastern Bumblebee', sci: 'Bombus impatiens', type: 'bee',
            role: 'Late-season nectar & pollen', note: 'Drought-tolerant old-field goldenrod feeds Eastern Bumblebees in dry habitats where most other flowers have wilted, extending the effective foraging territory of local colonies into roadsides and open fields.' },
          { name: 'Brown-belted Bumblebee', sci: 'Bombus griseocollis', type: 'bee',
            role: 'Late-season nectar & pollen', note: "Old-field goldenrod's tolerance for dry, disturbed soils means it blooms in roadsides and field margins where Brown-belted Bumblebees range widely — serving as a scattered network of fueling stations." },
          { name: 'American Bumblebee', sci: 'Bombus pensylvanicus', type: 'bee',
            role: 'Late-season nectar & pollen', note: 'Historically abundant in open grasslands, the American Bumblebee is strongly associated with old-field habitats. Goldenrod in these fields is among its most relied-upon late-season resources.' },
          { name: 'Painted Lady', sci: 'Vanessa cardui', type: 'butterfly',
            role: 'Nectar source', note: 'This migratory butterfly fuels on goldenrod during its fall southward movement. In years of high Painted Lady abundance, goldenrod fields can be alive with orange wings.' },
        ],
        wildlifeNote: 'Old field goldenrod is a cornerstone of meadow ecosystems. Planting it helps restore the connectivity of fragmented grassland habitat patches.',
        caterpillarSpp: 115,
        biosphereBonus: 7,
        cost: 22,
        duration: 7,
      },

      {
        id:               'wreath_goldenrod',
        requiresResearch: ['pollinator_survey'],
        name:             'Wreath Goldenrod',
        sci:  'Solidago caesia',
        icon: '🌿',
        type: 'flower',
        desc: 'Distinctive blue-green stem with small clusters of yellow flowers emerging along its full length — not just at the tip. One of the few goldenrods that grows well in full shade under large trees, filling a niche almost no other late-blooming plant occupies.',
        height: '2–3 ft',
        seasonOfInterest: 'Fall',
        insectsHosted: [
          { name: 'Eastern Bumblebee', sci: 'Bombus impatiens', type: 'bee',
            role: 'Late shaded-habitat nectar', note: 'Eastern Bumblebees forage readily at woodland edges, and wreath goldenrod is one of very few plants that brings fall nectar into the shaded woodland interior where they frequently roam.' },
          { name: 'Brown-belted Bumblebee', sci: 'Bombus griseocollis', type: 'bee',
            role: 'Late shaded-habitat nectar', note: "Woodland edge habitats are key foraging territory for Brown-belted Bumblebees. Wreath goldenrod's shade tolerance makes it uniquely valuable for sustaining these bees where sun-loving goldenrods cannot grow." },
          { name: 'American Bumblebee', sci: 'Bombus pensylvanicus', type: 'bee',
            role: 'Late shaded-habitat nectar', note: 'This declining species benefits from wreath goldenrod extending fall nectar into shaded habitats it frequently uses — hard-to-find resources that matter significantly for population survival.' },
          { name: 'Zephyr Sweat Bee', sci: 'Lasioglossum zephyrum', type: 'bee',
            role: 'Pollen & nectar', note: "Shade-adapted sweat bees are among the most frequent woodland-floor pollinators. On wreath goldenrod, the Zephyr Sweat Bee fills an ecological role that sun-loving bees simply cannot occupy." },
          { name: 'Broken-banded Sweat Bee', sci: 'Lasioglossum imitatum', type: 'bee',
            role: 'Pollen & nectar', note: 'In shaded garden settings, small sweat bees like L. imitatum often become the dominant visitor, returning to wreath goldenrod repeatedly for both pollen and nectar throughout the day.' },
          { name: 'Pearl Crescent', sci: 'Phyciodes tharos', type: 'butterfly',
            role: 'Nectar source', note: 'Even in dappled woodland light, Pearl Crescents find wreath goldenrod and add a final burst of colour to the late-season garden.' },
        ],
        wildlifeNote: 'The shaded habitat this plant occupies is critically underserved by late-season nectar sources. It acts as a bridge, connecting forest-interior insects to the same food web as open-meadow species.',
        caterpillarSpp: 115,
        biosphereBonus: 6,
        cost: 22,
        duration: 7,
      },

      {
        id:               'white_goldenrod',
        requiresResearch: ['pollinator_survey'],
        name:             'White Goldenrod',
        sci:  'Solidago bicolor',
        icon: '🤍',
        type: 'flower',
        desc: 'The only white-flowered goldenrod in eastern North America — an unusual sight among a sea of yellow. Blooms later than most goldenrods. Prefers dry, rocky, or sandy soils in open woodlands. The cream-white flowers are a useful way to attract goldenrod-specialists into ornamental plantings.',
        height: '1–3 ft',
        seasonOfInterest: 'Late Summer through Fall',
        insectsHosted: [
          { name: 'Goldenrod Plasterer Bee', sci: 'Colletes solidaginis', type: 'bee',
            role: 'Pollen specialist', note: 'Goldenrod Plasterer Bees locate their host by scent rather than colour — white goldenrod is chemically equivalent to yellow goldenrod. This species waterproofs its nest cells with a secreted polyester-like lining unique among bees.' },
          { name: 'Hairy-banded Mining Bee', sci: 'Andrena hirticincta', type: 'bee',
            role: 'Pollen specialist', note: 'This late-season Andrena species is a strict goldenrod pollen specialist, with adult females active only during the narrow window when goldenrods bloom. The dense hair bands on its abdomen are distinctive from other fall-active mining bees.' },
          { name: 'Eastern Bumblebee', sci: 'Bombus impatiens', type: 'bee',
            role: 'Late-season nectar', note: "White goldenrod's later bloom extends the nectar season into early fall, capturing Eastern Bumblebee queens still actively building fat stores before seeking a hibernation site." },
          { name: 'Brown-belted Bumblebee', sci: 'Bombus griseocollis', type: 'bee',
            role: 'Late-season nectar', note: 'The later bloom of white goldenrod relative to yellow goldenrods means Brown-belted Bumblebees find nectar here long after other goldenrod patches have gone to seed.' },
          { name: 'American Bumblebee', sci: 'Bombus pensylvanicus', type: 'bee',
            role: 'Late-season nectar', note: 'For the declining American Bumblebee, every extended bloom season matters. White goldenrod contributes a late-season buffer of resources that may improve colony overwinter survival rates.' },
        ],
        wildlifeNote: 'The pale flowers are distinctive in autumn. Like all goldenrods, the seed plumes provide winter food for finches and sparrows.',
        caterpillarSpp: 115,
        biosphereBonus: 6,
        cost: 20,
        duration: 7,
      },

      {
        id:               'grass_leaved_goldenrod',
        requiresResearch: ['pollinator_survey'],
        name:             'Grass-leaved Goldenrod',
        sci:  'Euthamia graminifolia',
        icon: '🌻',
        type: 'flower',
        desc: 'Dense, flat-topped clusters of tiny yellow flowers on narrow, grass-like leaves. Spreads by rhizomes to form colonies in moist meadows and wetland edges. A close relative of Solidago, it supports nearly the same insect community while occupying wetter microsites.',
        height: '2–4 ft',
        seasonOfInterest: 'Late Summer through Fall',
        insectsHosted: [
          { name: 'Goldenrod Plasterer Bee', sci: 'Colletes solidaginis', type: 'bee',
            role: 'Pollen specialist', note: 'Specialist bees locate goldenrod by scent rather than colour — Euthamia is chemically equivalent to Solidago and reliably attracts them. This species waterproofs its nest cells with a secreted polyester-like lining unique among bees.' },
          { name: 'Monarch', sci: 'Danaus plexippus', type: 'butterfly',
            role: 'Migration nectar', note: 'Monarchs passing through moist meadows and wetland edges in fall find this species where dry-habitat goldenrods don\'t grow.' },
          { name: 'Eastern Bumblebee', sci: 'Bombus impatiens', type: 'bee',
            role: 'Nectar & pollen', note: 'The flat-topped clusters of grass-leaved goldenrod are ideal landing platforms for larger bees. Eastern Bumblebees make rapid foraging runs across the dense flower heads, visiting dozens of florets per minute.' },
          { name: 'Zephyr Sweat Bee', sci: 'Lasioglossum zephyrum', type: 'bee',
            role: 'Nectar & pollen', note: "The small individual florets of Euthamia are perfectly sized for small native bees. The Zephyr Sweat Bee is among the most abundant fall visitors in the moist meadow settings where this plant thrives." },
          { name: 'Bicolored Sweat Bee', sci: 'Agapostemon virescens', type: 'bee',
            role: 'Nectar & pollen', note: 'With its metallic green head and striped abdomen, the Bicolored Sweat Bee is one of the most visually striking native bees visiting grass-leaved goldenrod along moist meadow and wetland edges.' },
        ],
        wildlifeNote: 'Where it grows in the moist margins of wetlands, it connects wet and dry habitat food webs by supporting the same suite of specialist insects in both environments.',
        caterpillarSpp: 100,
        biosphereBonus: 6,
        cost: 20,
        duration: 7,
      },

      {
        id:               'brown_eyed_susan',
        requiresResearch: ['pollinator_survey'],
        name:             'Brown-eyed Susan',
        sci:  'Rudbeckia triloba',
        icon: '🌸',
        type: 'flower',
        desc: 'A shorter, more prolific Rudbeckia with hundreds of small golden flowers with dark centres over a long blooming season. Short-lived perennial that self-seeds vigorously, creating self-sustaining colonies. More tolerant of shade than its relatives. Deer-resistant.',
        height: '2–5 ft',
        seasonOfInterest: 'Summer through Fall',
        insectsHosted: [
          { name: 'Silvery Checkerspot', sci: 'Chlosyne nycteis', type: 'butterfly',
            role: 'Specialist larval host', note: 'Silvery Checkerspot larvae live in communal groups on Rudbeckia foliage under a silk web, grazing together before dispersing individually to pupate.' },
          { name: 'Gorgone Checkerspot', sci: 'Chlosyne gorgone', type: 'butterfly',
            role: 'Larval host', note: 'A less common but equally specialized checkerspot whose caterpillars use both Rudbeckia and asters. Planting both plants dramatically increases the likelihood of local establishment.' },
          { name: 'Rudbeckia Mining Bee', sci: 'Andrena rudbeckiae', type: 'bee',
            role: 'Pollen specialist', note: 'Named for this genus, this mining bee collects pollen almost exclusively from Rudbeckia species. Nests in bare ground nearby and is active during the bloom window.' },
          { name: 'American Goldfinch', sci: 'Spinus tristis', type: 'bird',
            role: 'Seed consumer', note: 'Goldfinches cling acrobatically to the seed heads in autumn and winter, providing a compelling reason not to deadhead your Rudbeckia.' },
        ],
        wildlifeNote: 'The prolific seed production of Brown-Eyed Susan creates year-round resources: nectar and pollen in summer, seeds for birds in winter.',
        caterpillarSpp: 17,
        biosphereBonus: 6,
        cost: 22,
        duration: 10,
      },

      {
        id:               'black_eyed_susan',
        requiresResearch: ['pollinator_survey'],
        name:             'Black-eyed Susan',
        sci:  'Rudbeckia hirta',
        icon: '🌻',
        type: 'flower',
        desc: 'The iconic golden-rayed wildflower of North American meadows. A short-lived perennial that self-seeds and naturalises readily. Tolerates drought, poor soils, and full sun. Blooms from early summer through fall, providing an extraordinarily long window of support for insects. Deer-resistant. Container friendly.',
        height: '2–3 ft',
        seasonOfInterest: 'Summer through Fall',
        insectsHosted: [
          { name: 'Silvery Checkerspot', sci: 'Chlosyne nycteis', type: 'butterfly',
            role: 'Specialist larval host', note: 'The Silvery Checkerspot is one of the only butterflies whose larvae specialize on Rudbeckia. Without it, this striking black-and-orange butterfly cannot complete its life cycle.' },
          { name: 'Gorgone Checkerspot', sci: 'Chlosyne gorgone', type: 'butterfly',
            role: 'Larval host', note: 'This closely related checkerspot also uses Black-Eyed Susan as a larval host. Two specialist butterflies in one plant — a remarkable ecological concentration.' },
          { name: 'Rudbeckia Mining Bee', sci: 'Andrena rudbeckiae', type: 'bee',
            role: 'Pollen specialist', note: 'This small mining bee is functionally dependent on Rudbeckia. It nests alone in the ground, precisely timing its activity to Rudbeckia\'s bloom. It is invisible to most observers yet essential to the plant\'s seed set.' },
          { name: 'Gray Hairstreak', sci: 'Strymon melinus', type: 'butterfly',
            role: 'Larval host & nectar', note: 'Gray Hairstreak larvae bore into the flower heads of Black-Eyed Susan. Adults nectar widely on many flowers, but larval habitat is what limits their populations.' },
          { name: 'American Goldfinch', sci: 'Spinus tristis', type: 'bird',
            role: 'Seed consumer', note: 'Goldfinches are closely associated with Rudbeckia seed heads in late summer. Their bright yellow colouring and acrobatic feeding are inseparable from the image of a native wildflower meadow.' },
        ],
        wildlifeNote: 'Perhaps no native flower better demonstrates that ecological value and garden beauty are not in conflict. Cultivated Rudbeckia varieties support far fewer insects than the wild form.',
        caterpillarSpp: 17,
        biosphereBonus: 7,
        cost: 25,
        duration: 10,
      },

      {
        id:               'orange_coneflower',
        requiresResearch: ['pollinator_survey'],
        name:             'Orange Coneflower',
        sci:  'Rudbeckia fulgida',
        icon: '🌼',
        type: 'flower',
        desc: 'The most reliably perennial Rudbeckia, returning strongly each year from a spreading clump. Deep orange rays with a large dark cone. Tolerates clay soils and partial shade better than other coneflowers. Longer-lived than Black-Eyed Susan, making it better for a permanent naturalistic planting.',
        height: '2–3 ft',
        seasonOfInterest: 'Summer through Fall',
        insectsHosted: [
          { name: 'Silvery Checkerspot', sci: 'Chlosyne nycteis', type: 'butterfly',
            role: 'Specialist larval host', note: 'All three Rudbeckia species on this checklist support the Silvery Checkerspot. Planting a diverse suite ensures the butterfly has options across different garden microsites and bloom times.' },
          { name: 'Rudbeckia Mining Bee', sci: 'Andrena rudbeckiae', type: 'bee',
            role: 'Pollen specialist', note: 'The later and more reliable bloom of R. fulgida extends the window of specialized pollen availability for this ground-nesting bee, potentially supporting a second brood.' },
          { name: 'Eastern Bumblebee', sci: 'Bombus impatiens', type: 'bee',
            role: 'Nectar & pollen', note: 'Eastern Bumblebees work the large, accessible orange coneflower disks efficiently, often visiting hundreds of blooms in a single foraging bout through the patch.' },
          { name: 'Brown-belted Bumblebee', sci: 'Bombus griseocollis', type: 'bee',
            role: 'Nectar & pollen', note: "The reliably perennial nature of R. fulgida means Brown-belted Bumblebees return to the same patch year after year — treating it as a 'known good' feeding location within their foraging territory." },
          { name: 'American Bumblebee', sci: 'Bombus pensylvanicus', type: 'bee',
            role: 'Nectar & pollen', note: 'American Bumblebees forage strongly on coneflowers throughout summer. Supporting this declining species requires consistent, high-quality floral resources like orange coneflower across the full growing season.' },
          { name: 'American Goldfinch', sci: 'Spinus tristis', type: 'bird',
            role: 'Seed consumer', note: 'The tall, persistent seed cones of fulgida stay on the plant into winter, providing a reliable source of seeds after Rudbeckia hirta has finished.' },
        ],
        wildlifeNote: 'The perennial nature of this plant means it builds soil and habitat year over year, without the disturbance of replanting that resets insect colonization.',
        caterpillarSpp: 17,
        biosphereBonus: 7,
        cost: 25,
        duration: 10,
      },

      {
        id:               'common_evening_primrose',
        requiresResearch: ['wildflower_margins'],
        name:             'Common Evening Primrose',
        sci:  'Oenothera biennis',
        icon: '🌙',
        type: 'flower',
        desc: 'A biennial with large, luminous yellow flowers that open in the evening and close by mid-morning, releasing a sweet lemon scent to attract night-flying moths. Thrives in disturbed, sandy, or poor soils. A gateway plant to an often-overlooked nighttime ecology. Container friendly.',
        height: '3–6 ft',
        seasonOfInterest: 'Summer through Fall',
        insectsHosted: [
          { name: 'Primrose Moth', sci: 'Schinia florida', type: 'moth',
            role: 'Specialist: nectar, resting, egg-laying', note: 'This stunning rose-and-yellow moth rests on evening primrose flowers during the day and drinks nectar at night. Larvae develop inside the seed capsules. It is one of the most perfectly camouflaged insects in North America.' },
          { name: 'Hummingbird Clearwing Moth', sci: 'Hemaris thysbe', type: 'moth',
            role: 'Nectar source', note: 'This day-flying hawk-moth hovers and feeds exactly like a hummingbird — a miracle of convergent evolution. It is frequently misidentified. Evening primrose is among its preferred nectar sources.' },
          { name: 'Pandorus Sphinx', sci: 'Eumorpha pandorus', type: 'moth',
            role: 'Night nectar pollinator', note: 'This large, green-and-pink hawk-moth pollinates evening primrose with its long tongue, accessing nectar that most insects cannot reach. Its caterpillars feed on grape and Virginia creeper.' },
          { name: 'White-Lined Sphinx', sci: 'Hyles lineata', type: 'moth',
            role: 'Night pollinator', note: 'One of the most widespread hawk-moths in North America, visible at dusk hovering over evening primrose. Its fat caterpillars are important food for ground-nesting wasps and birds.' },
          { name: 'Zephyr Sweat Bee', sci: 'Lasioglossum zephyrum', type: 'bee',
            role: 'Early-morning nectar', note: 'As evening primrose flowers begin to close in the morning, early-rising Zephyr Sweat Bees arrive to gather the remaining pollen — a brief but productive foraging window that few other bees exploit.' },
          { name: 'Bicolored Sweat Bee', sci: 'Agapostemon virescens', type: 'bee',
            role: 'Early-morning nectar', note: 'The Bicolored Sweat Bee is a consistent morning visitor to evening primrose, collecting pollen from the overnight-opened flowers before the blooms close for the day.' },
        ],
        wildlifeNote: 'A plant that reveals an entirely different ecological world when observed after dark. The night-blooming guild of moths it supports does not exist anywhere in a conventional garden.',
        caterpillarSpp: 12,
        biosphereBonus: 7,
        cost: 22,
        duration: 10,
      },

      {
        id:               'woodland_sunflower',
        requiresResearch: ['bumblebee_habitat'],
        name:             'Woodland Sunflower',
        sci:  'Helianthus strumosus',
        icon: '☀️',
        type: 'flower',
        desc: 'A tall, spreading native sunflower that tolerates partial shade — unusual for the genus. Forms colonies via rhizomes. Pale green leaves and 3-inch golden flowers from midsummer through fall. An outstanding plant for filling the middle-canopy niche at a woodland edge.',
        height: '4–7 ft',
        seasonOfInterest: 'Summer through Fall',
        insectsHosted: [
          { name: 'Sunflower Specialist Bee', sci: 'Svastra obliqua', type: 'bee',
            role: 'Pollen specialist', note: 'Svastra obliqua is one of the most striking native bees — large, fuzzy, and covered in golden sunflower pollen. It is an obligate sunflower specialist and cannot reproduce without it.' },
          { name: 'Long-Horned Sunflower Bee', sci: 'Melissodes bimaculatus', type: 'bee',
            role: 'Pollen specialist', note: 'Males patrol sunflower patches all day and sleep on the stems at night. Both sexes collect pollen only from sunflowers during their brief late-summer active season.' },
          { name: 'Silvery Checkerspot', sci: 'Chlosyne nycteis', type: 'butterfly',
            role: 'Larval host', note: 'Checkerspot caterpillars readily use sunflower foliage alongside aster and Rudbeckia, making sunflowers an important backup host plant in diverse meadow plantings.' },
          { name: 'Painted Lady', sci: 'Vanessa cardui', type: 'butterfly',
            role: 'Larval host & nectar', note: 'Painted Lady larvae are among the most generalist of all butterfly caterpillars, using plants in the daisy family including sunflowers. Adults nectar on the blooms.' },
          { name: 'American Goldfinch', sci: 'Spinus tristis', type: 'bird',
            role: 'Seed consumer', note: 'Goldfinches cling to the large seed heads all through late summer and fall. A patch of native sunflowers is one of the most reliable ways to attract them to your garden.' },
        ],
        wildlifeNote: 'Native sunflowers support 73+ caterpillar species — compared to zero for the domestic commercial sunflower, which has been bred away from its ecological roles.',
        caterpillarSpp: 73,
        biosphereBonus: 8,
        cost: 28,
        duration: 14,
      },

      {
        id:               'swamp_sunflower',
        requiresResearch: ['bumblebee_habitat'],
        name:             'Swamp Sunflower',
        sci:  'Helianthus angustifolius',
        icon: '🌅',
        type: 'flower',
        desc: 'A tall, late-blooming sunflower of wet soils and low areas. Narrow, dark green leaves and masses of 2-inch golden flowers in October when almost nothing else is blooming. One of the most spectacular fall-flowering native plants for moist habitats.',
        height: '5–7 ft',
        seasonOfInterest: 'Fall',
        insectsHosted: [
          { name: 'Sunflower Specialist Bee', sci: 'Svastra obliqua', type: 'bee',
            role: 'Pollen specialist', note: 'This late-blooming sunflower captures Svastra bees just before they complete their season, extending their active period and potential brood production.' },
          { name: 'Monarch', sci: 'Danaus plexippus', type: 'butterfly',
            role: 'Late-season migration nectar', note: 'Swamp sunflower\'s October bloom means it catches Monarchs still moving through the landscape after goldenrod and boneset have largely finished.' },
          { name: 'Eastern Bumblebee', sci: 'Bombus impatiens', type: 'bee',
            role: 'Late nectar & pollen', note: 'Eastern Bumblebee queens strip pollen from swamp sunflower heads in October in a final push before hibernation. In wet areas, this is often the last substantial pollen source of the season.' },
          { name: 'Brown-belted Bumblebee', sci: 'Bombus griseocollis', type: 'bee',
            role: 'Late nectar & pollen', note: "Swamp sunflower's October bloom is one of the last pollen sources of the year. Brown-belted Bumblebee queens visit the large disk flowers repeatedly, maximizing fat storage in the final weeks before winter." },
          { name: 'American Bumblebee', sci: 'Bombus pensylvanicus', type: 'bee',
            role: 'Late nectar & pollen', note: 'The American Bumblebee is strongly associated with open, wet habitats — exactly where swamp sunflower thrives. This late-season overlap makes this plant especially important for this declining species.' },
          { name: 'American Goldfinch', sci: 'Spinus tristis', type: 'bird',
            role: 'Seed consumer', note: 'Goldfinches that have finished with earlier sunflower seeds migrate to swamp sunflower for its late harvest, following the bloom sequence across the landscape.' },
        ],
        wildlifeNote: 'The October bloom of swamp sunflower is ecologically irreplaceable — no non-native plant provides the same resources at the same time for the same community of insects.',
        caterpillarSpp: 73,
        biosphereBonus: 8,
        cost: 28,
        duration: 14,
      },

      {
        id:               'blanketflower',
        requiresResearch: ['wildflower_margins'],
        name:             'Blanketflower (Firewheel)',
        sci:  'Gaillardia pulchella',
        icon: '🔴',
        type: 'flower',
        desc: 'Fiery red and yellow bicolor blooms on airy stems from early summer through frost. Thrives in hot, dry, sandy soils. One of the toughest native wildflowers for difficult sites. Also called Firewheel for its resemblance to a spinning wheel of flames. Container friendly.',
        height: '1–2 ft',
        seasonOfInterest: 'Summer through Fall',
        insectsHosted: [
          { name: 'Gaillardia Specialist Bee', sci: 'Andrena helianthi', type: 'bee',
            role: 'Pollen specialist', note: 'This small mining bee collects pollen primarily from plants in the daisy family, with a specific preference for Gaillardia and sunflowers. It is a specialist of open, sunny, sandy habitats.' },
          { name: 'Common Longhorn Bee', sci: 'Melissodes communis', type: 'bee',
            role: 'Pollen source', note: 'One of the most frequently encountered Melissodes in the SE USA, the Common Longhorn Bee is a fast-moving forager that uses Gaillardia as one of its primary late-summer pollen sources.' },
          { name: 'Agile Longhorn Bee', sci: 'Melissodes agilis', type: 'bee',
            role: 'Pollen source', note: 'Males of this medium-sized native bee have conspicuously long antennae and are often the most numerous bee found sleeping on blanketflower stems on cool mornings before the day warms.' },
          { name: 'Sachem', sci: 'Atalopedes campestris', type: 'butterfly',
            role: 'Nectar source', note: 'One of the most abundant SE USA skippers of open, sunny habitats. Males perch conspicuously on blanketflower heads to establish territory. The large, open disk flowers are ideal landing platforms and nectar sources for this fast-flying skipper.' },
          { name: 'Fiery Skipper', sci: 'Hylephila phyleus', type: 'butterfly',
            role: 'Nectar source', note: 'An aptly named visitor to Firewheel — the Fiery Skipper is a warm grassland species whose bright orange-and-black patterning matches the flower\'s colour palette.' },
        ],
        wildlifeNote: 'One of few native plants that thrives in beach, roadside, and other severely dry or sandy habitats, making it ecologically important where conventional gardens cannot grow.',
        caterpillarSpp: 8,
        biosphereBonus: 5,
        cost: 20,
        duration: 7,
      },

      {
        id:               'lanceleaf_coreopsis',
        requiresResearch: ['bumblebee_habitat'],
        name:             'Lanceleaf Coreopsis',
        sci:  'Coreopsis lanceolata',
        icon: '🌞',
        type: 'flower',
        desc: 'The most drought-tolerant Coreopsis, with bright golden-yellow flowers on wiry stems above lance-shaped basal leaves. Forms low clumps that spread slowly and reseed freely in disturbed or sandy soil. An excellent gap-filler in dry meadow plantings. Container friendly.',
        height: '1–2 ft',
        seasonOfInterest: 'Spring through Summer',
        insectsHosted: [
          { name: 'Silvery Checkerspot', sci: 'Chlosyne nycteis', type: 'butterfly',
            role: 'Larval host', note: 'Checkerspot larvae use Coreopsis as a host alongside Rudbeckia and asters. Planting all three in proximity helps support a continuous larval habitat mosaic.' },
          { name: 'Gray Hairstreak', sci: 'Strymon melinus', type: 'butterfly',
            role: 'Larval host & nectar', note: 'Gray Hairstreak larvae feed on the flowers and seed pods of Coreopsis. This small copper-grey butterfly is easy to overlook but remarkably common where its hosts grow.' },
          { name: 'Common Longhorn Bee', sci: 'Melissodes communis', type: 'bee',
            role: 'Pollen source', note: 'One of the most efficient Coreopsis pollinators, the Common Longhorn Bee collects pollen and nectar simultaneously from the open disk flowers, often moving through an entire patch in a single fast-moving foraging bout.' },
          { name: 'Confusing Longhorn Bee', sci: 'Melissodes confusus', type: 'bee',
            role: 'Pollen source', note: 'Named for its close resemblance to related species, the Confusing Longhorn Bee is a frequent Coreopsis visitor throughout the SE USA, arriving in numbers when lanceleaf coreopsis reaches peak bloom.' },
          { name: 'American Goldfinch', sci: 'Spinus tristis', type: 'bird',
            role: 'Seed consumer', note: 'The small, flattened seeds of Coreopsis are a favourite of goldfinches in late summer. Allow the seed heads to mature and you\'ll have a bird feeder that restores itself.' },
        ],
        wildlifeNote: 'Coreopsis is the state wildflower of Florida. Where it grew historically, its disappearance has meant the local loss of Silvery Checkerspot populations.',
        caterpillarSpp: 12,
        biosphereBonus: 6,
        cost: 20,
        duration: 7,
      },

      {
        id:               'large_flower_tickseed',
        requiresResearch: ['bumblebee_habitat'],
        name:             'Large-flower Tickseed',
        sci:  'Coreopsis grandiflora',
        icon: '🌟',
        type: 'flower',
        desc: 'Larger, showier blooms than Lanceleaf Coreopsis, with fringed petals giving the flowers a slightly ragged, wild appearance that\'s actually more attractive to many insects. A short-lived perennial that self-seeds prolifically. One of the longest-blooming native wildflowers.',
        height: '1–2 ft',
        seasonOfInterest: 'Spring through Summer',
        insectsHosted: [
          { name: 'Silvery Checkerspot', sci: 'Chlosyne nycteis', type: 'butterfly',
            role: 'Larval host', note: 'The larger flower size of grandiflora means more oviposition sites for checkerspot females. A patch in bloom is worth pausing at to watch for egg-laying in early summer.' },
          { name: "Carlin's Mining Bee", sci: 'Andrena carlini', type: 'bee',
            role: 'Pollen source', note: "The fringed petals let bees access pollen from unusual angles. Carlin's Mining Bee is among the first miners to locate coreopsis each spring, nesting in garden paths and foraging the open flowers efficiently." },
          { name: "Nason's Mining Bee", sci: 'Andrena nasonii', type: 'bee',
            role: 'Pollen source', note: "A common SE USA spring miner, Nason's Mining Bee forages the fringed flowers of large-flower tickseed for pollen loads it carries in dense golden masses on its hind legs back to its nest." },
          { name: 'Eastern Bumblebee', sci: 'Bombus impatiens', type: 'bee',
            role: 'Nectar & pollen', note: "The large flowers of C. grandiflora are a preferred coreopsis species for Eastern Bumblebees due to the ease of landing and the generous pollen reward — visits are brief but highly productive." },
          { name: 'Brown-belted Bumblebee', sci: 'Bombus griseocollis', type: 'bee',
            role: 'Nectar & pollen', note: "Large-flower tickseed's early bloom means Brown-belted Bumblebees visit it in spring before many other summer wildflowers have opened — an early-season resource as colonies are rapidly expanding." },
          { name: 'American Bumblebee', sci: 'Bombus pensylvanicus', type: 'bee',
            role: 'Nectar & pollen', note: 'Coreopsis grandiflora blooms when American Bumblebee colonies are at their largest. Abundant pollen during peak colony growth can directly determine the size and health of the overwintering queen cohort.' },
        ],
        wildlifeNote: 'Because it blooms from spring into summer before most other natives, it fills a critical early-season gap between spring ephemerals and summer perennials.',
        caterpillarSpp: 12,
        biosphereBonus: 6,
        cost: 20,
        duration: 7,
      },

      {
        id:               'maryland_golden_aster',
        requiresResearch: ['bumblebee_habitat'],
        name:             'Maryland Golden-Aster',
        sci:  'Chrysopsis mariana',
        icon: '✨',
        type: 'flower',
        desc: 'Silvery-hairy leaves and clusters of bright yellow aster-like flowers in late summer through fall. Thrives in dry, sandy soils and full sun — conditions that challenge most native wildflowers. Named for its discovery in Maryland but ranges throughout the SE USA coastal plain and piedmont.',
        height: '1–2 ft',
        seasonOfInterest: 'Late Summer through Fall',
        insectsHosted: [
          { name: 'Hairy-banded Mining Bee', sci: 'Andrena hirticincta', type: 'bee',
            role: 'Pollen source', note: 'A fall-active specialist that synchronizes its adult flight season with the bloom of goldenrods and golden-asters. It nests in the same dry, sandy soils where Maryland Golden-Aster thrives — a plant and bee perfectly matched.' },
          { name: 'Ligated Furrow Bee', sci: 'Halictus ligatus', type: 'bee',
            role: 'Nectar & pollen', note: 'The most commonly encountered sweat bee in dry, open habitats of the SE coastal plain. It nests in bare sandy soil and is one of the last bees still actively foraging in late fall when golden-aster finishes blooming.' },
          { name: 'Zephyr Sweat Bee', sci: 'Lasioglossum zephyrum', type: 'bee',
            role: 'Nectar & pollen', note: 'In the dry, sunny habitats where Maryland Golden-Aster specializes, the Zephyr Sweat Bee is a consistent and frequent visitor throughout the late-summer and fall bloom period.' },
          { name: "Horace's Duskywing", sci: 'Erynnis horatius', type: 'butterfly',
            role: 'Nectar source', note: 'One of the most common spread-wing skippers of dry, sandy SE USA habitats — exactly the conditions where Maryland Golden-Aster thrives. Males perch on bare ground and low vegetation between nectar visits, making this plant a reliable observation spot for the species.' },
        ],
        wildlifeNote: 'Dry sandy soils are among the most underserved native plant habitats. Maryland Golden-Aster fills this niche elegantly while also supporting the specialist insect community of those environments.',
        caterpillarSpp: 10,
        biosphereBonus: 5,
        cost: 20,
        duration: 7,
      },

      // ══ SHRUBS/SMALL TREES ═════════════════════════════════════════════════

      {
        id:               'smooth_alder',
        requiresResearch: ['hedgerow_seeding'],
        name:             'Smooth Alder',
        sci:  'Alnus serrulata',
        icon: '🌿',
        type: 'shrub',
        desc: 'A multi-stemmed shrub or small tree of stream banks, pond margins, and wet swales. Pendulous catkins in early spring are among the first pollen sources of the year. As a nitrogen-fixing plant, it improves soil wherever it grows — a rare quality among woody plants.',
        height: '10–15 ft',
        seasonOfInterest: 'Early Spring (catkins)',
        insectsHosted: [
          { name: 'Eastern Comma', sci: 'Polygonia comma', type: 'butterfly',
            role: 'Specialist larval host', note: 'The Eastern Comma is named for the small silver comma mark on its hindwing. Its caterpillars are specialists on plants in the birch family, including alder. Without riparian shrubs, this butterfly vanishes from the local landscape.' },
          { name: 'Question Mark', sci: 'Polygonia interrogationis', type: 'butterfly',
            role: 'Larval host', note: 'A close relative of the Eastern Comma, the Question Mark also uses alder and elm as a larval host. Both butterflies overwinter as adults and are among the first butterflies visible in early spring.' },
          { name: 'Polyphemus Moth', sci: 'Antheraea polyphemus', type: 'moth',
            role: 'Larval host', note: 'One of North America\'s largest and most beautiful moths, with eyespot wing markings that startled vertebrate predators. Its caterpillars feed on alder, oak, maple, and birch. Seeing one in your yard is a measure of true habitat quality.' },
          { name: 'American Woodcock', sci: 'Scolopax minor', type: 'bird',
            role: 'Nesting habitat', note: 'This beloved and bizarre shorebird that lives in forests uses alder thickets as primary nesting and brooding habitat. The males perform their "sky dance" courtship display in openings adjacent to alder groves at dawn and dusk.' },
          { name: 'Eastern Bumblebee', sci: 'Bombus impatiens', type: 'bee',
            role: 'Early-spring pollen', note: 'Bumble bee queens emerging from winter are among the first to harvest alder catkin pollen — critical for fueling the solitary nest-founding phase before other spring flowers open.' },
          { name: "Carlin's Mining Bee", sci: 'Andrena carlini', type: 'bee',
            role: 'Early-spring pollen', note: "One of the earliest mining bees to emerge in spring, Carlin's Mining Bee times its season to overlap with alder catkin availability — collecting the protein-rich pollen that jumpstarts its nesting season." },
        ],
        wildlifeNote: 'As a nitrogen fixer, smooth alder builds soil fertility that benefits neighbouring plants. Its roots stabilize streambanks, preventing erosion. A 15-foot shrub supports an entire community.',
        caterpillarSpp: 255,
        biosphereBonus: 12,
        cost: 55,
        duration: 21,
      },

      {
        id:               'bear_oak',
        requiresResearch: ['hedgerow_seeding'],
        name:             'Bear Oak',
        sci:  'Quercus ilicifolia',
        icon: '🌳',
          hasFruit: true,
        type: 'shrub',
        desc: 'A slow-growing dwarf oak that rarely exceeds 10 feet, forming dense thickets in dry, rocky, or sandy soils. Its small acorns are produced in abundance and are critically important for wildlife. Adapted to fire-dependent ecosystems and tolerant of conditions that defeat other oaks.',
        height: '5–10 ft',
        seasonOfInterest: 'Year-round wildlife value',
        insectsHosted: [
          { name: 'King\'s Hairstreak', sci: 'Satyrium kingi', type: 'butterfly',
            role: 'Specialist larval host', note: 'This regionally rare butterfly is almost exclusively associated with bear oak in the southeastern coastal plain. Where bear oak habitat is lost, King\'s Hairstreak disappears. Planting bear oak is a direct conservation act for this species.' },
          { name: 'Edward\'s Hairstreak', sci: 'Satyrium edwardsii', type: 'butterfly',
            role: 'Specialist larval host', note: 'Another oak hairstreak specialist found in scrub habitats. Both Edward\'s and King\'s Hairstreaks lay eggs on bare oak twigs and the larvae hatch to feed on new growth in spring.' },
          { name: 'Banded Hairstreak', sci: 'Satyrium calanus', type: 'butterfly',
            role: 'Larval host', note: 'The most widespread oak-feeding hairstreak in the SE USA. Adults are often seen nectaring at the top of large trees but are easier to observe on shrubby bear oak where they are closer to eye level.' },
          { name: 'Imperial Moth', sci: 'Eacles imperialis', type: 'moth',
            role: 'Larval host', note: 'One of North America\'s most spectacular moths — yellow and purple with bold eyespots — the Imperial Moth is strongly associated with oaks across the SE USA. Its massive caterpillars feed on oak, pine, and maple. Bear oak supports the full complement of 500+ oak Lepidoptera; the Imperial Moth is the crown jewel.' },
          { name: 'Red-headed Woodpecker', sci: 'Melanerpes erythrocephalus', type: 'bird',
            role: 'Acorn cacher', note: 'This striking woodpecker caches acorns in bark crevices and in the ground. It is declining rapidly and is now a species of conservation concern. Bear oak\'s abundant small acorns are a primary food source.' },
        ],
        wildlifeNote: 'Bear oak demonstrates that tree size is no indicator of ecological value. This low thicket-forming shrub supports an oak food web comparable to trees ten times its height.',
        caterpillarSpp: 557,
        biosphereBonus: 15,
        cost: 70,
        duration: 30,
      },

      // ══ TREES ══════════════════════════════════════════════════════════════

      {
        id:               'pitch_pine',
        requiresResearch: ['prairie_grass_patches'],
        name:             'Pitch Pine',
        sci:  'Pinus rigida',
        icon: '🌲',
        type: 'tree',
        desc: 'A rugged, fire-adapted pine of the coastal plain and piedmont with distinctive twisted needles in groups of three and persistent, spiny cones. Exceptionally tolerant of drought, fire, poor soils, and salt spray. The defining tree of pine barrens ecosystems.',
        height: '40–60 ft',
        seasonOfInterest: 'Year-round wildlife value',
        insectsHosted: [
          { name: 'Pine Elfin', sci: 'Callophrys niphon', type: 'butterfly',
            role: 'Specialist larval host', note: 'The Pine Elfin is a specialist that lays its eggs only on young pine growth. Its caterpillars are perfectly camouflaged against pine needles. In landscapes without pines, this butterfly does not exist.' },
          { name: 'Eastern Pine Elfin', sci: 'Callophrys niphon', type: 'butterfly',
            role: 'Specialist — new growth feeder', note: 'Adults are active for only 3–4 weeks in early spring, visiting flowers of wild cherries and serviceberries near pines. Their entire dependence on pine makes every planted specimen significant.' },
          { name: 'Pine Barrens Zanclognatha', sci: 'Zanclognatha martha', type: 'moth',
            role: 'Specialist larval host', note: 'A federally threatened moth restricted to pitch pine barrens. Its caterpillars depend on pine litter and duff — not the living needles — making undisturbed ground under pines as important as the tree itself.' },
          { name: 'Pine Warbler', sci: 'Setophaga pinus', type: 'bird',
            role: 'Foraging & nesting specialist', note: 'The Pine Warbler is one of few warblers that stays year-round, nesting in pine canopy and foraging almost exclusively in pines. It is the most pine-associated bird in the SE USA.' },
          { name: 'Brown-headed Nuthatch', sci: 'Sitta pusilla', type: 'bird',
            role: 'Cavity nesting specialist', note: 'This small, tool-using bird uses bark flakes to pry open pine bark in search of insects. It is a SE USA pine forest specialist that is declining with loss of mature pine stands.' },
        ],
        wildlifeNote: 'Pitch pine supports more than 200 caterpillar species and provides specialized habitat for declining birds of the SE coastal plain. Planting one is an act of ecoregion-specific conservation.',
        caterpillarSpp: 203,
        biosphereBonus: 16,
        cost: 85,
        duration: 45,
      },

      {
        id:               'river_birch',
        requiresResearch: ['prairie_grass_patches'],
        name:             'River Birch',
        sci:  'Betula nigra',
        icon: '🌿',
        type: 'tree',
        desc: 'The heat-tolerant birch of the Southeast, with peeling cinnamon-to-cream bark that gives year-round ornamental interest. Fast-growing and short-lived compared to other shade trees, but produces enormous quantities of seeds and supports hundreds of insect species. Prefers moist soils along waterways.',
        height: '40–70 ft',
        seasonOfInterest: 'Year-round wildlife value',
        insectsHosted: [
          { name: 'Eastern Comma', sci: 'Polygonia comma', type: 'butterfly',
            role: 'Specialist larval host', note: 'Birch is one of the Eastern Comma\'s primary larval hosts. Adults are stunning — textured russet wings with that tiny silver comma underneath — and are among the first butterflies to appear in spring as they overwinter as adults.' },
          { name: 'Question Mark', sci: 'Polygonia interrogationis', type: 'butterfly',
            role: 'Larval host', note: 'The Question Mark\'s larger wingspan and additional silver hindwing mark distinguish it from the Comma. Both species use river birch and can be found together on the same tree.' },
          { name: 'Mourning Cloak', sci: 'Nymphalis antiopa', type: 'butterfly',
            role: 'Larval host', note: 'Mourning Cloak caterpillars feed gregariously on birch, willow, and elm, then disperse to pupate alone. The adults are spectacular — dark maroon wings edged with yellow and blue spots — and live up to 10 months, the longest-lived butterfly in North America.' },
          { name: 'Dreamy Duskywing', sci: 'Erynnis icelus', type: 'butterfly',
            role: 'Specialist larval host', note: 'This small, brown skipper is a birch and willow specialist. Easy to overlook, it is an indicator species for intact riparian woodland corridors.' },
          { name: 'Luna Moth', sci: 'Actias luna', type: 'moth',
            role: 'Larval host', note: 'One of the most spectacular moths in the world, the Luna Moth feeds on birch, walnut, and sweet gum as a caterpillar. Adults live only a week and don\'t eat at all — their entire adult life is devoted to reproduction. A Luna in your yard is a sign of excellent habitat quality.' },
          { name: 'American Goldfinch', sci: 'Spinus tristis', type: 'bird',
            role: 'Seed consumer', note: 'Birch seeds are tiny and produced in enormous quantities by pendulous catkins. Goldfinches and redpolls flock to birch for these seeds from late summer well into winter.' },
        ],
        wildlifeNote: 'River birch hosts 413+ caterpillar species — more than nearly any other tree in the SE USA. Its ecological contribution rivals that of oaks in riparian corridors.',
        caterpillarSpp: 413,
        biosphereBonus: 20,
        cost: 90,
        duration: 60,
      },

      {
        id:               'blackjack_oak',
        requiresResearch: ['bird_boxes'],
        name:             'Blackjack Oak',
        sci:  'Quercus marilandica',
          hasFruit: true,
        icon: '🌳',
        type: 'tree',
        desc: 'A small, scrubby oak of dry upland and sandy soils, recognizable by its distinctive club- or duck-shaped leaves. One of the most drought-tolerant oaks in the SE USA, thriving in conditions that stress larger oaks. Often forms thickets on poor soils alongside post oak. A keystone species of fire-adapted savannas.',
        height: '20–30 ft',
        seasonOfInterest: 'Year-round wildlife value',
        insectsHosted: [
          { name: 'Horace\'s Duskywing', sci: 'Erynnis horatius', type: 'butterfly',
            role: 'Specialist larval host', note: 'This skip is one of several "oak duskywings" whose larvae feed exclusively on oak foliage. Horace\'s Duskywing is the most common of the trio in the SE and uses a broad range of oak species including Blackjack.' },
          { name: 'Juvenal\'s Duskywing', sci: 'Erynnis juvenalis', type: 'butterfly',
            role: 'Specialist larval host', note: 'One of the earliest butterflies to appear in spring, using freshly emerged oak leaves as larval food. Adults are boldly patterned in grey and black and often seen perching on oak bark.' },
          { name: 'White M Hairstreak', sci: 'Parrhasius m-album', type: 'butterfly',
            role: 'Specialist larval host', note: 'This brilliant jewel-blue hairstreak is strictly an oak specialist. The "M" in its name refers to a marking on its hindwing. It is a SE USA native that does not venture far from oaks.' },
          { name: 'Banded Hairstreak', sci: 'Satyrium calanus', type: 'butterfly',
            role: 'Larval host', note: 'Banded Hairstreaks are common on all SE USA oaks. Adults nectar on milkweed and dogbane in midsummer. Their caterpillars eat young oak foliage in spring and then the adults emerge a few months later.' },
          { name: 'Imperial Moth', sci: 'Eacles imperialis', type: 'moth',
            role: 'Larval host', note: 'A magnificent yellow-and-purple moth with a 5-inch wingspan. Its large, dark caterpillars pupate in the soil and feed on oak, pine, and maple. Adults do not eat and live only a few days. Declining due to light pollution.' },
        ],
        wildlifeNote: 'Blackjack oak forms the structural backbone of longleaf pine savannas and scrub oak ecosystems alongside post oak — some of the most endangered habitat types in the SE USA.',
        caterpillarSpp: 534,
        biosphereBonus: 22,
        cost: 100,
        duration: 75,
      },

      {
        id:               'red_maple',
        requiresResearch: ['prairie_grass_patches'],
        name:             'Red Maple',
        sci:  'Acer rubrum',
        icon: '🍁',
        type: 'tree',
        desc: 'The most abundant tree in eastern North America. Provides brilliant red foliage in autumn and clusters of small red flowers in late winter — often the very first tree to bloom each year. Adaptable to a wide range of soils from wet to dry. A cornerstone of the eastern deciduous forest.',
        height: '40–60 ft',
        seasonOfInterest: 'Late Winter (flowers) & Fall (colour)',
        insectsHosted: [
          { name: 'Rosy Maple Moth', sci: 'Dryocampa rubicunda', type: 'moth',
            role: 'Specialist larval host', note: 'One of the most beautiful moths in North America — candy-pink and lemon-yellow — the Rosy Maple Moth feeds exclusively on maples as a caterpillar. Seeing one at your porch light is a direct reward for planting red maple.' },
          { name: 'Columbia Silkmoth', sci: 'Hyalophora columbia', type: 'moth',
            role: 'Larval host', note: 'A large silkmoth that feeds on red maple and larch. Rare enough that an encounter feels like finding treasure. Like all silkmoths, adults do not feed at all — their fat caterpillars bank all needed energy reserves.' },
          { name: 'Cecropia Moth', sci: 'Hyalophora cecropia', type: 'moth',
            role: 'Larval host', note: 'North America\'s largest native moth, with a wingspan exceeding 7 inches. Pale red, white, and black wings that look like velvet. Caterpillars eat red maple, wild cherry, and birch. Light pollution significantly reduces egg-laying success.' },
          { name: 'Eastern Comma', sci: 'Polygonia comma', type: 'butterfly',
            role: 'Larval host', note: 'One of several Polygonia butterflies that uses maple as a secondary larval host alongside elm and nettle. Adults seen at maple flower nectar in early spring are often the same individuals that overwintered as adults nearby.' },
          { name: 'Ruby-throated Hummingbird', sci: 'Archilochus colubris', type: 'bird',
            role: 'Nectar source & early-spring fuel', note: 'Red maple flowers produce nectar nearly a month before most other plants. Hummingbirds migrating north in early spring are completely dependent on these flowers and on sapsucker wells in maple trunks. This is one of the most important early-spring wildlife resources in the east.' },
        ],
        wildlifeNote: 'Red maple flowers provide critical early nectar before almost every other plant has bloomed, supporting queen bumble bees emerging from overwintering. 285+ caterpillar species depend on it.',
        caterpillarSpp: 285,
        biosphereBonus: 20,
        cost: 90,
        duration: 60,
      },

      {
        id:               'shagbark_hickory',
        requiresResearch: ['bird_boxes'],
        name:             'Shagbark Hickory',
        sci:  'Carya ovata',
        icon: '🌰',
          hasFruit: true,
        type: 'tree',
        desc: 'Named for its dramatic, shaggy exfoliating bark that forms long, loose plates. One of the most distinctive trees in the eastern forest. Produces the finest-flavoured native nut in North America. A long-lived, slow-to-establish tree that becomes ecologically invaluable with age.',
        height: '60–80 ft',
        seasonOfInterest: 'Fall (nuts)',
        insectsHosted: [
          { name: 'Hickory Hairstreak', sci: 'Satyrium caryaevorus', type: 'butterfly',
            role: 'Specialist larval host', note: 'The species name caryaevorus means "eater of Carya" and says it all: this hairstreak is strictly a hickory specialist. Rare and declining with the loss of mature hickory trees from the landscape.' },
          { name: 'Banded Hairstreak', sci: 'Satyrium calanus', type: 'butterfly',
            role: 'Larval host', note: 'Banded Hairstreaks use both hickory and oak as larval hosts, though in some parts of their range hickory is strongly preferred. Adults nectar on meadow plants far from their larval trees.' },
          { name: 'Imperial Moth', sci: 'Eacles imperialis', type: 'moth',
            role: 'Larval host', note: 'This spectacular moth\'s caterpillars feed on hickory, oak, and pine. The 4-inch pale green caterpillars are fringed with long lateral filaments that make them unmistakable if you find one.' },
          { name: 'Luna Moth', sci: 'Actias luna', type: 'moth',
            role: 'Larval host', note: 'Luna Moth caterpillars feed on hickory, walnut, and birch. On shagbark hickory specifically, the overwintering cocoons can be found tucked under the loose bark plates — a remarkable example of using a unique tree feature for survival.' },
          { name: 'Eastern Fox Squirrel', sci: 'Sciurus niger', type: 'mammal',
            role: 'Nut cacher', note: 'Fox squirrels cache hickory nuts and often fail to retrieve all of them, directly reseeding hickory into new areas. They are declining alongside the large, open forests they require — including hickory parkland.' },
        ],
        wildlifeNote: 'Shagbark hickory\'s slow growth is an investment in long-term ecological capital. A 50-year-old tree supports a wildlife community that cannot be replicated by any other tree or group of plants.',
        caterpillarSpp: 219,
        biosphereBonus: 18,
        cost: 90,
        duration: 75,
      },

      {
        id:               'post_oak',
        requiresResearch: ['bird_boxes'],
        name:             'Post Oak',
        sci:  'Quercus stellata',
          hasFruit: true,
        icon: '🌳',
        type: 'tree',
        desc: 'A medium-sized oak of dry uplands, ridges, and sandy soils. Slower-growing than other oaks but enormously long-lived, with some specimens exceeding 400 years. Cross-shaped leaves are immediately distinctive. Co-dominant with blackjack oak in the fire-adapted "Cross Timbers" ecosystem of SE and south-central USA.',
        height: '35–50 ft',
        seasonOfInterest: 'Year-round wildlife value',
        insectsHosted: [
          { name: 'Juvenal\'s Duskywing', sci: 'Erynnis juvenalis', type: 'butterfly',
            role: 'Specialist larval host', note: 'Post oak\'s early leafout in dry upland settings provides the first oak foliage available in these habitats — exactly when Juvenal\'s Duskywing needs it in early spring.' },
          { name: 'Horace\'s Duskywing', sci: 'Erynnis horatius', type: 'butterfly',
            role: 'Specialist larval host', note: 'The most common SE oak duskywing uses post oak readily. In the cross timbers ecosystem, post oak and blackjack oak together are the sole larval habitat. Lose the oaks, lose the butterflies.' },
          { name: 'Gray Hairstreak', sci: 'Strymon melinus', type: 'butterfly',
            role: 'Larval host & nectar', note: 'Perhaps the most generalist hairstreak, the Gray uses oaks among many larval hosts. But oak is where it thrives in dry upland habitats where other host plants are scarce.' },
          { name: 'White Oak Skimmer', sci: 'Libellula luctuosa', type: 'beetle',
            role: 'Ecological indicator', note: 'Woodland dragonflies and beetles associated with oak canopy are among the least-studied but most ecologically significant users of oak trees. The oak canopy is an entire separate ecosystem.' },
          { name: 'Wild Turkey', sci: 'Meleagris gallopavo', type: 'bird',
            role: 'Acorn consumer', note: 'Wild turkeys are among the most important seed dispersers for oaks. They consume acorns by the hundreds and their wandering routes spread oak seeds across the landscape. In the SE, post oak acorns are a primary fall food source.' },
        ],
        wildlifeNote: 'Post oak\'s deep taproot makes it extraordinarily drought-tolerant once established. Long-lived individuals create old-growth canopy features that younger forests cannot replicate for decades.',
        caterpillarSpp: 534,
        biosphereBonus: 22,
        cost: 100,
        duration: 75,
      },

      {
        id:               'black_oak',
        requiresResearch: ['bat_roosts'],
        name:             'Black Oak',
        sci:  'Quercus velutina',
          hasFruit: true,
        icon: '🌲',
        type: 'tree',
        desc: 'A large, impressive red oak with deeply lobed, glossy leaves and especially dark bark giving it its name. One of the fastest-growing large oaks. Notable for producing quercitron, a yellow dye once commercially extracted from its inner bark. An ecologically dominant species of the upland oak-hickory forest.',
        height: '50–80 ft',
        seasonOfInterest: 'Year-round wildlife value',
        insectsHosted: [
          { name: 'White M Hairstreak', sci: 'Parrhasius m-album', type: 'butterfly',
            role: 'Specialist larval host', note: 'Black oak is a preferred host for this iridescent-blue gem of a butterfly. Its canopy-dwelling adults can be hard to spot, but the occasional individual descends to nectar at mid-level flowers — watch especially around milkweed.' },
          { name: 'Banded Hairstreak', sci: 'Satyrium calanus', type: 'butterfly',
            role: 'Larval host', note: 'Commonly found on black oak; adults are among the most accessible oak hairstreaks, often nectaring near the ground on milkweed and dogbane in midsummer.' },
          { name: 'Polyphemus Moth', sci: 'Antheraea polyphemus', type: 'moth',
            role: 'Larval host', note: 'The caterpillars of this beautiful, eyespot-bearing silkmoth are found on black oak throughout summer. Adults are nocturnal and can be lured to porch lights, where their 5-inch wingspan stops people in their tracks.' },
          { name: 'Spiny Oakworm Moth', sci: 'Anisota stigma', type: 'moth',
            role: 'Specialist larval host', note: 'These large, gregarious caterpillars feed communally on oak foliage and are important food for cuckoos and other insectivorous birds. They are so specialized on black oak that their populations mirror oak abundance directly.' },
          { name: 'Blue Jay', sci: 'Cyanocitta cristata', type: 'bird',
            role: 'Acorn cacher and disperser', note: 'Blue jays are among the most important dispersers of oak seeds in eastern North America. Each fall individual jays cache hundreds of acorns far from the parent tree, regenerating oak forests in a radius that no other mechanism can match.' },
        ],
        wildlifeNote: 'Black oak is the most aggressive large-acorn oak in the eastern upland, providing huge caloric resources for wildlife. Its fast growth makes it practical for impact within a gardener\'s lifetime.',
        caterpillarSpp: 534,
        biosphereBonus: 22,
        cost: 100,
        duration: 75,
      },

      {
        id:               'white_oak',
        requiresResearch: ['hedgehog_highways'],
        name:             'White Oak',
        sci:  'Quercus alba',
        icon: '🏔️',
          hasFruit: true,
        type: 'tree',
        desc: 'The ecological crown jewel of eastern North America. White Oak supports more species of caterpillars (557+) than any other tree genus in the region. A majestic, wide-canopied tree that can live 500+ years. Its sweet acorns (low tannin) are the preferred food of dozens of wildlife species and have historically fed humans, too.',
        height: '50–80 ft',
        seasonOfInterest: 'Year-round wildlife value',
        insectsHosted: [
          { name: '557+ Caterpillar Species', sci: 'Multiple Lepidoptera', type: 'moth',
            role: 'Larval host — every guild', note: 'No other plant in the eastern USA supports more butterfly and moth species. Every category from tiny micromoths to 7-inch silkmoths includes oak specialists. A single white oak in a suburban yard supports more caterpillar biodiversity than an acre of ornamental landscaping.' },
          { name: 'Banded Hairstreak', sci: 'Satyrium calanus', type: 'butterfly',
            role: 'Specialist larval host', note: 'The most common of the oak hairstreaks, reliably found wherever white oaks grow. Adults nectar at milkweed and dogbane. The year begins and ends with oak: eggs are laid in autumn and hatch the following spring.' },
          { name: 'Juvenal\'s Duskywing', sci: 'Erynnis juvenalis', type: 'butterfly',
            role: 'Specialist larval host', note: 'One of spring\'s first butterflies, active as soon as oak buds break. Its larvae consume tender new leaves that have just emerged — remarkable timing evolved over millions of years alongside oak phenology.' },
          { name: 'Polyphemus Moth', sci: 'Antheraea polyphemus', type: 'moth',
            role: 'Larval host', note: 'White oak is a preferred host of this stunning silkmoth. The large, silk-spun cocoons can be found attached to branches. An emerged adult sitting on oak bark is a spectacle of natural beauty.' },
          { name: 'Wood Duck', sci: 'Aix sponsa', type: 'bird',
            role: 'Acorn specialist & cavity nester', note: 'Wood Ducks nest in cavities of old oaks near water and feed heavily on white oak acorns in fall. Their comeback from near-extinction is one of conservation\'s greatest success stories — driven partly by the preservation of large old oaks near water.' },
          { name: 'Red-headed Woodpecker', sci: 'Melanerpes erythrocephalus', type: 'bird',
            role: 'Acorn cacher & cavity excavator', note: 'Once common, now a species of serious concern. Red-headed Woodpeckers cache acorns in bark crevices for winter and nest in dead oak snags. Maintaining old oaks — including their dead wood — is central to this bird\'s recovery.' },
        ],
        wildlifeNote: 'Doug Tallamy calls white oak "the most important tree you can plant in eastern North America." It is ecologically irreplaceable. Planting one is a multi-generational gift to the local food web.',
        caterpillarSpp: 557,
        biosphereBonus: 30,
        cost: 120,
        duration: 90,
      },

      {
        id:               'black_willow',
        requiresResearch: ['bat_roosts'],
        name:             'Black Willow',
        sci:  'Salix nigra',
        icon: '🌿',
        type: 'tree',
        desc: 'The largest native willow in North America. Fast-growing and short-lived, with graceful, drooping branches and narrow leaves. A colonizer of stream banks, pond margins, and floodplains, stabilizing soil and filtering runoff. Early-spring catkins are among the first substantial pollen sources of the year.',
        height: '30–60 ft',
        seasonOfInterest: 'Early Spring (catkins) & Year-round',
        insectsHosted: [
          { name: 'Viceroy', sci: 'Limenitis archippus', type: 'butterfly',
            role: 'Specialist larval host', note: 'The Viceroy is one of ecology\'s great examples. Long described as a Monarch "mimic," research now shows it is equally unpalatable — both species benefit from resembling each other. Its caterpillars feed exclusively on willow and aspen foliage.' },
          { name: 'Mourning Cloak', sci: 'Nymphalis antiopa', type: 'butterfly',
            role: 'Larval host', note: 'Mourning Cloak caterpillars live gregariously on willow branches, moving together to feed. Adults of this species can live nearly a year — overwintering as adults and visiting willow flowers in early spring.' },
          { name: 'Red-spotted Purple', sci: 'Limenitis arthemis', type: 'butterfly',
            role: 'Larval host', note: 'A stunning iridescent-blue admiral butterfly whose caterpillars feed on willow, cherry, and aspen. It can hybridize with the White Admiral in the North. Its larval use of willow means stream corridors are essential corridors for this species.' },
          { name: 'Polyphemus Moth', sci: 'Antheraea polyphemus', type: 'moth',
            role: 'Larval host', note: 'Willow is among this silkmoth\'s preferred larval hosts. Its eyespot markings — mimicking owl eyes to startle predators — are as striking as anything in nature. A moth whose welfare depends directly on the abundance of willows near water.' },
          { name: 'Yellow Warbler', sci: 'Setophaga petechia', type: 'bird',
            role: 'Nesting specialist', note: 'Yellow Warblers show a strong preference for nesting in willows near water. The abundant caterpillars on willow foliage provide the insect-rich food source their chicks require — a food web connection in plain sight.' },
        ],
        wildlifeNote: 'Willows host 455+ caterpillar species and provide early-spring pollen for queen bumble bees in a period when nearly nothing else blooms. Their root systems also protect streambanks from erosion better than any engineered solution.',
        caterpillarSpp: 455,
        biosphereBonus: 24,
        cost: 100,
        duration: 60,
      },

      {
        id:               'black_cherry',
        requiresResearch: ['hedgehog_highways'],
        name:             'Black Cherry',
        sci:  'Prunus serotina',
        icon: '🍒',
          hasFruit: true,
        type: 'tree',
        desc: 'The most ecologically valuable tree in the cherry genus. Fragrant white flowers in spring, small dark fruits that are irresistible to birds, and brilliant orange-red fall colour. Grows widely across the SE USA in forests and disturbed areas. Second only to oaks in the number of Lepidoptera species it supports.',
        height: '50–80 ft',
        seasonOfInterest: 'Spring (flowers) & Summer (fruit)',
        insectsHosted: [
          { name: 'Eastern Tiger Swallowtail', sci: 'Papilio glaucus', type: 'butterfly',
            role: 'Specialist larval host', note: 'The SE USA\'s most familiar large butterfly. Its caterpillars feed on black cherry, tulip poplar, and sweet bay magnolia. Every Tiger Swallowtail you\'ve ever seen as an adult was once a caterpillar largely dependent on black cherry.' },
          { name: 'Coral Hairstreak', sci: 'Satyrium titus', type: 'butterfly',
            role: 'Specialist larval host', note: 'One of the only hairstreaks with no tails on its hindwing. Strictly a cherry specialist, it lays its eggs at the base of cherry bark and the larvae hatch in spring to climb and feed on new leaves. A beautiful butterfly most people have never seen.' },
          { name: 'Striped Hairstreak', sci: 'Satyrium liparops', type: 'butterfly',
            role: 'Larval host', note: 'A modest, small hairstreak whose larvae use cherry, oak, and blueberry. Adults nectar near their host trees in midsummer. Easy to miss but consistently present where cherry grows.' },
          { name: 'Red-spotted Purple', sci: 'Limenitis arthemis', type: 'butterfly',
            role: 'Larval host', note: 'This iridescent blue and red butterfly uses cherry as a primary larval host in the SE USA. Its caterpillars make conspicuous "frass chains" by attaching their droppings to a silk line — a behaviour unique to this genus.' },
          { name: 'Cecropia Moth', sci: 'Hyalophora cecropia', type: 'moth',
            role: 'Larval host', note: 'North America\'s largest moth uses black cherry as one of its preferred larval hosts alongside maple and birch. The cocoon, woven directly onto a cherry twig, is a winter wonder to find. A yard with Cecropia is a yard with excellent ecological credentials.' },
        ],
        wildlifeNote: 'Over 43 bird species eat black cherry fruit, more than any other native tree. Cedar Waxwings, American Robins, and Hermit Thrushes strip the branches. The tree hosts 456+ caterpillar species — the avian food web depends on it.',
        caterpillarSpp: 456,
        biosphereBonus: 25,
        cost: 110,
        duration: 75,
      },

    ], // end plants
  }, // end SE USA Plains ecoregion
];

// ── Helper: look up a plant by ID across all ecoregions ──────────────────────
export function findPlant(plantId) {
  for (const eco of ECOREGIONS) {
    const plant = eco.plants.find(p => p.id === plantId);
    if (plant) return { plant, ecoregion: eco };
  }
  return null;
}
