// invasives.js — Invasive species database for Idle Ecologist
// Real-world invasive species of the SE USA Plains ecoregion (8.3).
// Each species occupies a portion of the player's 1000-acre property at game
// start and must be removed through conservation research + CP expenditure.

export const INVASIVE_CATEGORIES = {
  plant:  { id: 'plant',  label: '🌿 Invasive Plants',  desc: 'Non-native plants that displace native species and degrade habitat.' },
  animal: { id: 'animal', label: '🐾 Invasive Animals', desc: 'Non-native animals that damage ecosystems and compete with native wildlife.' },
};

/**
 * @typedef {Object} InvasiveSpecies
 * @property {string}  id              - Unique identifier
 * @property {string}  name            - Common name
 * @property {string}  sci             - Scientific name
 * @property {string}  icon            - Emoji icon
 * @property {'plant'|'animal'} type   - Category
 * @property {1|2|3}   tier            - 1=minor, 2=medium, 3=dominant
 * @property {string}  desc            - Educational description
 * @property {string}  damage          - What ecological damage it causes
 * @property {string}  controlMethod   - Real-world removal strategy (flavor text for research)
 * @property {number}  baseAcres       - Starting acres at game start
 * @property {number}  removeCpPerAcre - Conservation points to clear one acre
 * @property {number}  removeTimeDays  - In-game days per acre for timed (queued) removal
 * @property {number}  instantRemoveMax - Up to this many acres can be removed instantly per action
 * @property {number}  regrowthRate    - Daily probability of re-invading one adjacent empty acre
 * @property {string|null} requiredResearch - ID of the research project that unlocks removal
 */

export const INVASIVES = [

  // ══ DOMINANT (tier 3) ═══════════════════════════════════════════════════════

  {
    id:               'kudzu',
    name:             'Kudzu',
    sci:              'Pueraria montana var. lobata',
    icon:             '🌿',
    type:             'plant',
    tier:             3,
    desc:             'The "vine that ate the South." Introduced from Japan in 1876 as an ornamental and promoted for erosion control, kudzu now blankets an estimated 7.4 million acres across the southeastern United States. It can grow up to a foot per day in summer.',
    damage:           'Smothers native vegetation, trees, and structures by blocking all sunlight. Forms monoculture stands that eliminate every native plant, insect, and animal that depended on the original habitat.',
    controlMethod:    'Repeated cutting (2–3× per year minimum), prescribed burning, herbicide application to fresh-cut stems, and goat grazing. Root crowns must be completely removed — any fragment can regenerate.',
    baseAcres:        150,
    removeCpPerAcre:  12,
    removeTimeDays:   5,
    instantRemoveMax: 3,
    regrowthRate:     0.03,
    requiredResearch: 'deep_root_eradication',
  },
  {
    id:               'chinese_privet',
    name:             'Chinese Privet',
    sci:              'Ligustrum sinense',
    icon:             '🪵',
    type:             'plant',
    tier:             3,
    desc:             'The most widespread invasive plant in the southeastern U.S. forestlands. Introduced as an ornamental hedge plant, it has spread relentlessly via bird-dispersed berries into virtually every forest type in the region.',
    damage:           'Forms impenetrable thickets 10–20 feet tall that exclude all understory plants. Releases allelopathic chemicals that prevent competitor germination. Eliminates the shrub and groundcover layers that songbirds, box turtles, and native pollinators depend on.',
    controlMethod:    'Hand-pulling saplings, chainsaw clearing of mature stands followed by targeted herbicide (triclopyr) on cut stumps, repeated burning to reset growth, and goat grazing for maintenance.',
    baseAcres:        140,
    removeCpPerAcre:  11,
    removeTimeDays:   5,
    instantRemoveMax: 3,
    regrowthRate:     0.03,
    requiredResearch: 'deep_root_eradication',
  },
  {
    id:               'cogongrass',
    name:             'Cogongrass',
    sci:              'Imperata cylindrica',
    icon:             '🔥',
    type:             'plant',
    tier:             3,
    desc:             'Listed as one of the world\'s ten worst invasive weeds by the IUCN. This aggressive tropical grass was accidentally introduced to Alabama around 1912 in packing material and has been spreading ever since.',
    damage:           'Forms dense monoculture grasslands that increase wildfire frequency and intensity — its fires burn hotter than native grass fires, killing native trees. Eliminates habitat for ground-nesting birds, gopher tortoises, and native bunchgrasses.',
    controlMethod:    'Repeated mowing (every 4 weeks during growing season), intensive herbicide (imazapyr applied to fresh cuts), prescribed burning followed by herbicide, and soil inversion for small patches. Requires multi-year commitment.',
    baseAcres:        130,
    removeCpPerAcre:  11,
    removeTimeDays:   5,
    instantRemoveMax: 3,
    regrowthRate:     0.025,
    requiredResearch: 'deep_root_eradication',
  },
  {
    id:               'feral_hogs',
    name:             'Feral Hogs',
    sci:              'Sus scrofa',
    icon:             '🐗',
    type:             'animal',
    tier:             3,
    desc:             'Descended from escaped domestic pigs and Eurasian wild boar, feral hogs are among the most destructive invasive animals in the U.S. Their population in the Southeast has exploded to an estimated 6+ million, causing $1.5 billion in damage annually.',
    damage:           'Rooting behavior destroys soil structure, uproots native plants and seeds, creates wallows that breed mosquitoes, competes with native wildlife for acorns and mast, and preys on ground-nesting birds, reptiles, and salamanders.',
    controlMethod:    'Year-round hunting (no bag limit in most SE states), corral trapping, aerial gunning, fencing exclusion from sensitive restoration areas, and targeted removal programs. Requires sustained aggressive control — they can produce two litters per year.',
    baseAcres:        120,
    removeCpPerAcre:  14,
    removeTimeDays:   6,
    instantRemoveMax: 2,
    regrowthRate:     0.035,
    requiredResearch: 'large_fauna_control',
  },

  // ══ MEDIUM (tier 2) ════════════════════════════════════════════════════════

  {
    id:               'japanese_stiltgrass',
    name:             'Japanese Stiltgrass',
    sci:              'Microstegium vimineum',
    icon:             '🌾',
    type:             'plant',
    tier:             2,
    desc:             'Also called Nepalese browntop, this annual grass was first documented in Tennessee in 1919, likely introduced as packing material. It now infests forests, floodplains, and roadsides across the entire Southeast.',
    damage:           'Forms dense mats that outcompete native wildflowers and spring ephemerals, reduces seed germination of native plants, and rapidly colonizes any disturbed ground. Deer avoid it, giving it a further competitive edge.',
    controlMethod:    'Hand-pulling before seed set (August–September), targeted grass-selective herbicide (sethoxydim), prescribed burning in late fall, and repeated mowing before seed production. Being annual, one good season of control helps.',
    baseAcres:        60,
    removeCpPerAcre:  6,
    removeTimeDays:   3,
    instantRemoveMax: 5,
    regrowthRate:     0.02,
    requiredResearch: 'vine_groundcover_control',
  },
  {
    id:               'autumn_olive',
    name:             'Autumn Olive',
    sci:              'Elaeagnus umbellata',
    icon:             '🍂',
    type:             'plant',
    tier:             2,
    desc:             'Ironically promoted by the USDA Soil Conservation Service in the 1940s–60s for erosion control and wildlife food, autumn olive is now recognized as a major invasive. It fixes nitrogen, changing soil chemistry to favor its own spread.',
    damage:           'Dense thickets shade out the understory, displacing native shrubs that birds and pollinators depend on. Berries are spread far and wide by birds, establishing new populations in open areas and into forests.',
    controlMethod:    'Hand-pulling saplings, cutting followed by immediate herbicide (triclopyr) on stumps, repeated cutting to exhaust root reserves, and prescribed burning. Can be controlled with consistent effort over 2–3 years.',
    baseAcres:        55,
    removeCpPerAcre:  7,
    removeTimeDays:   3,
    instantRemoveMax: 5,
    regrowthRate:     0.018,
    requiredResearch: 'woody_invasive_removal',
  },
  {
    id:               'japanese_honeysuckle',
    name:             'Japanese Honeysuckle',
    sci:              'Lonicera japonica',
    icon:             '🍃',
    type:             'plant',
    tier:             2,
    desc:             'Introduced from East Asia in 1806 as an ornamental and for erosion control. Its sweet-smelling flowers are familiar to anyone who grew up in the South, but its beauty masks enormous ecological damage.',
    damage:           'Aggressive climbing and spreading vine that smothers the shrub layer and lower tree canopy, suppressing seedling establishment and spring wildflowers. Evergreen in the South, maintaining a competitive advantage through winter.',
    controlMethod:    'Hand-pulling vines from small areas, cutting and herbicide (glyphosate or triclopyr) application on cut stems, repeated cutting cycles, burning, and dense native wildflower plantings to outcompete.',
    baseAcres:        50,
    removeCpPerAcre:  6,
    removeTimeDays:   3,
    instantRemoveMax: 5,
    regrowthRate:     0.02,
    requiredResearch: 'vine_groundcover_control',
  },
  {
    id:               'mimosa',
    name:             'Mimosa (Silk Tree)',
    sci:              'Albizia julibrissin',
    icon:             '🌳',
    type:             'plant',
    tier:             2,
    desc:             'A fast-growing nitrogen-fixing tree from Asia, introduced to the U.S. in 1745 as an ornamental. Its fluffy pink flowers and ferny leaves are attractive but conceal an aggressive invader.',
    damage:           'Spreads via prodigious seed production — pods burst and scatter seeds widely. Grows rapidly to shade out native trees, fixes nitrogen to alter soil chemistry, and creates a depauperate understory where little else can grow.',
    controlMethod:    'Cutting followed by immediate herbicide stump treatment, targeted removal before seed set, repeated cutting to deplete root reserves, and prescribed burning. Individual trees are easy; populations require sustained effort.',
    baseAcres:        45,
    removeCpPerAcre:  7,
    removeTimeDays:   3,
    instantRemoveMax: 5,
    regrowthRate:     0.015,
    requiredResearch: 'woody_invasive_removal',
  },
  {
    id:               'chinese_tallow',
    name:             'Chinese Tallow Tree',
    sci:              'Triadica sebifera',
    icon:             '💛',
    type:             'plant',
    tier:             2,
    desc:             'Introduced by Benjamin Franklin in 1776 for its waxy seed coating (used to make candles and soap). Now one of the most aggressively spreading invasive trees in the coastal Southeast.',
    damage:           'Releases allelopathic compounds that prevent competing plant growth. Produces copious seeds dispersed by birds. Forms monoculture stands in wet areas and uplands. Seeds remain viable in the soil for years.',
    controlMethod:    'Cutting with herbicide stump treatment (triclopyr), foliar herbicide application, burning, and mechanical removal. The persistent seed bank requires long-term management over multiple years.',
    baseAcres:        40,
    removeCpPerAcre:  8,
    removeTimeDays:   4,
    instantRemoveMax: 4,
    regrowthRate:     0.02,
    requiredResearch: 'woody_invasive_removal',
  },
  {
    id:               'multiflora_rose',
    name:             'Multiflora Rose',
    sci:              'Rosa multiflora',
    icon:             '🌹',
    type:             'plant',
    tier:             2,
    desc:             'Introduced from Japan in 1866 as rootstock for ornamental roses and later promoted by the USDA for "living fences" and erosion control. Now classified as a noxious weed in most southeastern states.',
    damage:           'Dense thorny thickets impenetrable to large animals, displaces native shrubs, and forms barrier stands along roadsides and forest edges. Each plant can produce 500,000 seeds per year, spread by birds.',
    controlMethod:    'Hand-pulling small plants (with heavy gloves!), repeated cutting to exhaust root reserves, targeted herbicide (triclopyr) on stumps, prescribed burning, and potential biological control via rose-rosette virus.',
    baseAcres:        35,
    removeCpPerAcre:  7,
    removeTimeDays:   3,
    instantRemoveMax: 5,
    regrowthRate:     0.015,
    requiredResearch: 'woody_invasive_removal',
  },
  {
    id:               'fire_ants',
    name:             'Red Imported Fire Ant',
    sci:              'Solenopsis invicta',
    icon:             '🐜',
    type:             'animal',
    tier:             2,
    desc:             'Accidentally introduced to Mobile, Alabama around 1930 via ship ballast. These South American ants have since spread across the entire Southeast, with densities reaching 200+ mounds per acre in heavily infested areas.',
    damage:           'Aggressive competitor that displaces native ant species, reducing invertebrate diversity by up to 90% in infested areas. Painful stings cause medical emergencies for livestock, pets, and people. Preys on ground-nesting bird chicks and reptile hatchlings.',
    controlMethod:    'Broadcast baiting programs (spinosad or hydramethylnon), individual mound treatment with approved insecticides, habitat management to reduce soil disturbance, and biological control research using parasitic phorid flies.',
    baseAcres:        35,
    removeCpPerAcre:  8,
    removeTimeDays:   4,
    instantRemoveMax: 4,
    regrowthRate:     0.025,
    requiredResearch: 'invasive_pest_management',
  },

  // ══ MINOR (tier 1) ═════════════════════════════════════════════════════════

  {
    id:               'bradford_pear',
    name:             'Bradford Pear',
    sci:              'Pyrus calleryana',
    icon:             '🌸',
    type:             'plant',
    tier:             1,
    desc:             'Once the most-planted ornamental tree in America, Bradford pear was considered sterile — until cross-pollination with other Callery pear cultivars produced fertile fruit. Several SE states have now banned their sale.',
    damage:           'Thorny, dense-branching hybrid offspring escape from landscapes and form thickets in open fields. Crowds out native trees and shrubs. Weak wood structure causes limb breakage in storms.',
    controlMethod:    'Cutting and herbicide (triclopyr) on stumps, girdling to kill standing trees, and prevention in residential landscapes. South Carolina\'s "Bradford Pear Bounty" program pays citizens to replace them with natives.',
    baseAcres:        25,
    removeCpPerAcre:  4,
    removeTimeDays:   2,
    instantRemoveMax: 8,
    regrowthRate:     0.01,
    requiredResearch: 'invasive_plant_survey',
  },
  {
    id:               'nandina',
    name:             'Nandina (Heavenly Bamboo)',
    sci:              'Nandina domestica',
    icon:             '🎋',
    type:             'plant',
    tier:             1,
    desc:             'A common landscaping shrub from East Asia, found in almost every Southern subdivision. Despite its ornamental popularity, its bright red berries are toxic to cedar waxwings and other birds and its seeds spread readily into natural areas.',
    damage:           'Spreads via bird-dispersed berries into woodlands and forest edges where it forms shade-excluding thickets. Berries contain cyanide compounds — documented mass die-offs of cedar waxwings have been attributed to nandina berry consumption.',
    controlMethod:    'Hand-pulling small plants and seedlings (very effective), cutting larger plants with herbicide on stumps, and prevention by removing from residential landscapes. Easier to control than most invasives when caught early.',
    baseAcres:        25,
    removeCpPerAcre:  3,
    removeTimeDays:   1,
    instantRemoveMax: 10,
    regrowthRate:     0.008,
    requiredResearch: 'invasive_plant_survey',
  },
  {
    id:               'english_ivy',
    name:             'English Ivy',
    sci:              'Hedera helix',
    icon:             '🍀',
    type:             'plant',
    tier:             1,
    desc:             'Brought to America by colonial settlers as a nostalgic reminder of English estates. Now one of the most problematic invasive plants in southeastern forests, particularly in urban and suburban woodlands.',
    damage:           'Dense groundcover excludes native wildflowers and ferns. Climbs trees and weakens them by added weight, reduces photosynthesis, and makes them susceptible to windthrow. Creates a homogeneous carpet that eliminates structural diversity.',
    controlMethod:    'Hand-pulling (very labor-intensive but effective for small areas), cutting vines at tree bases ("tree saving"), herbicide application (glyphosate) to fresh-cut stems, and repeated cutting cycles over 2–3 years.',
    baseAcres:        20,
    removeCpPerAcre:  5,
    removeTimeDays:   2,
    instantRemoveMax: 6,
    regrowthRate:     0.012,
    requiredResearch: 'vine_groundcover_control',
  },
  {
    id:               'wisteria',
    name:             'Wisteria',
    sci:              'Wisteria sinensis',
    icon:             '💜',
    type:             'plant',
    tier:             1,
    desc:             'Chinese wisteria was introduced in 1816 as a flowering ornamental vine. Its spectacular purple blooms mask one of the most persistent woody vine invasions in southeastern forests.',
    damage:           'Climbs trees to the canopy, adding enormous weight and shading the understory. Strangles host trees over time. Aggressive vegetative spread via runners creates vine curtains in woodlands.',
    controlMethod:    'Cutting vines at the base and pulling from trees, targeted herbicide (triclopyr) on cut stems, repeated cutting to exhaust root reserves, and prevention of seed production by removing pods.',
    baseAcres:        15,
    removeCpPerAcre:  5,
    removeTimeDays:   2,
    instantRemoveMax: 6,
    regrowthRate:     0.01,
    requiredResearch: 'vine_groundcover_control',
  },
  {
    id:               'lesser_celandine',
    name:             'Lesser Celandine',
    sci:              'Ficaria verna',
    icon:             '🌼',
    type:             'plant',
    tier:             1,
    desc:             'A low-growing European perennial that was Wordsworth\'s favourite flower. In the Southeast, it emerges in late winter before any native wildflowers, carpeting floodplains and moist woodlands with glossy yellow flowers.',
    damage:           'Outcompetes native spring ephemerals (trilliums, bloodroot, Virginia bluebells) by leafing out and blooming earlier. Creates dense carpets via underground tubers and bulbils that are nearly impossible to eradicate completely.',
    controlMethod:    'Hand-digging to remove tubers (spring and fall), very early spring herbicide application (glyphosate before natives emerge), native species replanting, and repeated removal cycles over 2–3 years.',
    baseAcres:        20,
    removeCpPerAcre:  4,
    removeTimeDays:   2,
    instantRemoveMax: 8,
    regrowthRate:     0.01,
    requiredResearch: 'invasive_plant_survey',
  },
  {
    id:               'asian_tiger_mosquito',
    name:             'Asian Tiger Mosquito',
    sci:              'Aedes albopictus',
    icon:             '🦟',
    type:             'animal',
    tier:             1,
    desc:             'Arrived in the U.S. in 1985 via used tire shipments from Asia at the port of Houston. This aggressive daytime biter has since spread across the entire Southeast and is now the most common container-breeding mosquito in urban areas.',
    damage:           'Vectors of dengue, Zika, chikungunya, and other diseases. More aggressive than native mosquitoes, biting primarily during daylight hours. Outcompetes native mosquito species for breeding habitat in small water containers.',
    controlMethod:    'Elimination of standing water (source reduction — tires, saucers, gutters), targeted larvicide (Bti) in permanent water features, community education, and integrated pest management. Prevention is far more effective than reactive spraying.',
    baseAcres:        15,
    removeCpPerAcre:  6,
    removeTimeDays:   3,
    instantRemoveMax: 5,
    regrowthRate:     0.02,
    requiredResearch: 'invasive_pest_management',
  },
  {
    id:               'spotted_lanternfly',
    name:             'Spotted Lanternfly',
    sci:              'Lycorma delicatula',
    icon:             '🦗',
    type:             'animal',
    tier:             1,
    desc:             'A beautiful but devastating planthopper native to China and Vietnam, first detected in Pennsylvania in 2014. It is actively expanding southward into the Southeast, with established populations now confirmed in several states.',
    damage:           'Sap-sucking pest that weakens trees and crops, producing copious honeydew that promotes sooty mold growth. Threatens grapes, peaches, apples, and hardwood forests. Each female lays 30–50 eggs in masses on any flat surface.',
    controlMethod:    'Quarantine and inspection to prevent spread, scraping and destroying egg masses, sticky bands on trees to trap nymphs, removal of tree-of-heaven (preferred host), targeted insecticide spraying, and early detection reporting.',
    baseAcres:        10,
    removeCpPerAcre:  5,
    removeTimeDays:   2,
    instantRemoveMax: 5,
    regrowthRate:     0.015,
    requiredResearch: 'invasive_pest_management',
  },
];

// ── Lookup helpers ────────────────────────────────────────────────────────────
export const INVASIVE_MAP = Object.fromEntries(INVASIVES.map(s => [s.id, s]));

/** Total starting invaded acres (should sum to 990). */
export const TOTAL_INVADED_ACRES = INVASIVES.reduce((sum, s) => sum + s.baseAcres, 0);

export function findInvasive(id) {
  return INVASIVE_MAP[id] ?? null;
}
